/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JobStatusDto } from './JobStatusDto';
import {
    JobStatusDtoFromJSON,
    JobStatusDtoFromJSONTyped,
    JobStatusDtoToJSON,
} from './JobStatusDto';

/**
 * 
 * @export
 * @interface AllJobStatusResponseDto
 */
export interface AllJobStatusResponseDto {
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    backgroundTask: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    faceDetection: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    facialRecognition: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    library: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    metadataExtraction: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    migration: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    search: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    sidecar: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    smartSearch: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    storageTemplateMigration: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    thumbnailGeneration: JobStatusDto;
    /**
     * 
     * @type {JobStatusDto}
     * @memberof AllJobStatusResponseDto
     */
    videoConversion: JobStatusDto;
}

/**
 * Check if a given object implements the AllJobStatusResponseDto interface.
 */
export function instanceOfAllJobStatusResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "backgroundTask" in value;
    isInstance = isInstance && "faceDetection" in value;
    isInstance = isInstance && "facialRecognition" in value;
    isInstance = isInstance && "library" in value;
    isInstance = isInstance && "metadataExtraction" in value;
    isInstance = isInstance && "migration" in value;
    isInstance = isInstance && "search" in value;
    isInstance = isInstance && "sidecar" in value;
    isInstance = isInstance && "smartSearch" in value;
    isInstance = isInstance && "storageTemplateMigration" in value;
    isInstance = isInstance && "thumbnailGeneration" in value;
    isInstance = isInstance && "videoConversion" in value;

    return isInstance;
}

export function AllJobStatusResponseDtoFromJSON(json: any): AllJobStatusResponseDto {
    return AllJobStatusResponseDtoFromJSONTyped(json, false);
}

export function AllJobStatusResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllJobStatusResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'backgroundTask': JobStatusDtoFromJSON(json['backgroundTask']),
        'faceDetection': JobStatusDtoFromJSON(json['faceDetection']),
        'facialRecognition': JobStatusDtoFromJSON(json['facialRecognition']),
        'library': JobStatusDtoFromJSON(json['library']),
        'metadataExtraction': JobStatusDtoFromJSON(json['metadataExtraction']),
        'migration': JobStatusDtoFromJSON(json['migration']),
        'search': JobStatusDtoFromJSON(json['search']),
        'sidecar': JobStatusDtoFromJSON(json['sidecar']),
        'smartSearch': JobStatusDtoFromJSON(json['smartSearch']),
        'storageTemplateMigration': JobStatusDtoFromJSON(json['storageTemplateMigration']),
        'thumbnailGeneration': JobStatusDtoFromJSON(json['thumbnailGeneration']),
        'videoConversion': JobStatusDtoFromJSON(json['videoConversion']),
    };
}

export function AllJobStatusResponseDtoToJSON(value?: AllJobStatusResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'backgroundTask': JobStatusDtoToJSON(value.backgroundTask),
        'faceDetection': JobStatusDtoToJSON(value.faceDetection),
        'facialRecognition': JobStatusDtoToJSON(value.facialRecognition),
        'library': JobStatusDtoToJSON(value.library),
        'metadataExtraction': JobStatusDtoToJSON(value.metadataExtraction),
        'migration': JobStatusDtoToJSON(value.migration),
        'search': JobStatusDtoToJSON(value.search),
        'sidecar': JobStatusDtoToJSON(value.sidecar),
        'smartSearch': JobStatusDtoToJSON(value.smartSearch),
        'storageTemplateMigration': JobStatusDtoToJSON(value.storageTemplateMigration),
        'thumbnailGeneration': JobStatusDtoToJSON(value.thumbnailGeneration),
        'videoConversion': JobStatusDtoToJSON(value.videoConversion),
    };
}

