/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CQMode = {
    Auto: 'auto',
    Cqp: 'cqp',
    Icq: 'icq'
} as const;
export type CQMode = typeof CQMode[keyof typeof CQMode];


export function CQModeFromJSON(json: any): CQMode {
    return CQModeFromJSONTyped(json, false);
}

export function CQModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CQMode {
    return json as CQMode;
}

export function CQModeToJSON(value?: CQMode | null): any {
    return value as any;
}

