/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JobCommand } from './JobCommand';
import {
    JobCommandFromJSON,
    JobCommandFromJSONTyped,
    JobCommandToJSON,
} from './JobCommand';

/**
 * 
 * @export
 * @interface JobCommandDto
 */
export interface JobCommandDto {
    /**
     * 
     * @type {JobCommand}
     * @memberof JobCommandDto
     */
    command: JobCommand;
    /**
     * 
     * @type {boolean}
     * @memberof JobCommandDto
     */
    force: boolean;
}

/**
 * Check if a given object implements the JobCommandDto interface.
 */
export function instanceOfJobCommandDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "command" in value;
    isInstance = isInstance && "force" in value;

    return isInstance;
}

export function JobCommandDtoFromJSON(json: any): JobCommandDto {
    return JobCommandDtoFromJSONTyped(json, false);
}

export function JobCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobCommandDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'command': JobCommandFromJSON(json['command']),
        'force': json['force'],
    };
}

export function JobCommandDtoToJSON(value?: JobCommandDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'command': JobCommandToJSON(value.command),
        'force': value.force,
    };
}

