/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutResponseDto
 */
export interface LogoutResponseDto {
    /**
     * 
     * @type {string}
     * @memberof LogoutResponseDto
     */
    redirectUri: string;
    /**
     * 
     * @type {boolean}
     * @memberof LogoutResponseDto
     */
    successful: boolean;
}

/**
 * Check if a given object implements the LogoutResponseDto interface.
 */
export function instanceOfLogoutResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "redirectUri" in value;
    isInstance = isInstance && "successful" in value;

    return isInstance;
}

export function LogoutResponseDtoFromJSON(json: any): LogoutResponseDto {
    return LogoutResponseDtoFromJSONTyped(json, false);
}

export function LogoutResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'redirectUri': json['redirectUri'],
        'successful': json['successful'],
    };
}

export function LogoutResponseDtoToJSON(value?: LogoutResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'redirectUri': value.redirectUri,
        'successful': value.successful,
    };
}

