/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetResponseDto } from './AssetResponseDto';
import {
    AssetResponseDtoFromJSON,
    AssetResponseDtoFromJSONTyped,
    AssetResponseDtoToJSON,
} from './AssetResponseDto';

/**
 * 
 * @export
 * @interface MemoryLaneResponseDto
 */
export interface MemoryLaneResponseDto {
    /**
     * 
     * @type {Array<AssetResponseDto>}
     * @memberof MemoryLaneResponseDto
     */
    assets: Array<AssetResponseDto>;
    /**
     * 
     * @type {string}
     * @memberof MemoryLaneResponseDto
     */
    title: string;
}

/**
 * Check if a given object implements the MemoryLaneResponseDto interface.
 */
export function instanceOfMemoryLaneResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "assets" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function MemoryLaneResponseDtoFromJSON(json: any): MemoryLaneResponseDto {
    return MemoryLaneResponseDtoFromJSONTyped(json, false);
}

export function MemoryLaneResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryLaneResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assets': ((json['assets'] as Array<any>).map(AssetResponseDtoFromJSON)),
        'title': json['title'],
    };
}

export function MemoryLaneResponseDtoToJSON(value?: MemoryLaneResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assets': ((value.assets as Array<any>).map(AssetResponseDtoToJSON)),
        'title': value.title,
    };
}

