/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserAvatarColor } from './UserAvatarColor';
import {
    UserAvatarColorFromJSON,
    UserAvatarColorFromJSONTyped,
    UserAvatarColorToJSON,
} from './UserAvatarColor';

/**
 * 
 * @export
 * @interface PartnerResponseDto
 */
export interface PartnerResponseDto {
    /**
     * 
     * @type {UserAvatarColor}
     * @memberof PartnerResponseDto
     */
    avatarColor: UserAvatarColor;
    /**
     * 
     * @type {Date}
     * @memberof PartnerResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PartnerResponseDto
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    externalPath: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerResponseDto
     */
    inTimeline?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerResponseDto
     */
    isAdmin: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerResponseDto
     */
    memoriesEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    oauthId: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    profileImagePath: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerResponseDto
     */
    quotaSizeInBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof PartnerResponseDto
     */
    quotaUsageInBytes: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerResponseDto
     */
    shouldChangePassword: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerResponseDto
     */
    storageLabel: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PartnerResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PartnerResponseDto interface.
 */
export function instanceOfPartnerResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "avatarColor" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "deletedAt" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "externalPath" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isAdmin" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "oauthId" in value;
    isInstance = isInstance && "profileImagePath" in value;
    isInstance = isInstance && "quotaSizeInBytes" in value;
    isInstance = isInstance && "quotaUsageInBytes" in value;
    isInstance = isInstance && "shouldChangePassword" in value;
    isInstance = isInstance && "storageLabel" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function PartnerResponseDtoFromJSON(json: any): PartnerResponseDto {
    return PartnerResponseDtoFromJSONTyped(json, false);
}

export function PartnerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatarColor': UserAvatarColorFromJSON(json['avatarColor']),
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] === null ? null : new Date(json['deletedAt'])),
        'email': json['email'],
        'externalPath': json['externalPath'],
        'id': json['id'],
        'inTimeline': !exists(json, 'inTimeline') ? undefined : json['inTimeline'],
        'isAdmin': json['isAdmin'],
        'memoriesEnabled': !exists(json, 'memoriesEnabled') ? undefined : json['memoriesEnabled'],
        'name': json['name'],
        'oauthId': json['oauthId'],
        'profileImagePath': json['profileImagePath'],
        'quotaSizeInBytes': json['quotaSizeInBytes'],
        'quotaUsageInBytes': json['quotaUsageInBytes'],
        'shouldChangePassword': json['shouldChangePassword'],
        'storageLabel': json['storageLabel'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PartnerResponseDtoToJSON(value?: PartnerResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatarColor': UserAvatarColorToJSON(value.avatarColor),
        'createdAt': (value.createdAt.toISOString()),
        'deletedAt': (value.deletedAt === null ? null : value.deletedAt.toISOString()),
        'email': value.email,
        'externalPath': value.externalPath,
        'id': value.id,
        'inTimeline': value.inTimeline,
        'isAdmin': value.isAdmin,
        'memoriesEnabled': value.memoriesEnabled,
        'name': value.name,
        'oauthId': value.oauthId,
        'profileImagePath': value.profileImagePath,
        'quotaSizeInBytes': value.quotaSizeInBytes,
        'quotaUsageInBytes': value.quotaUsageInBytes,
        'shouldChangePassword': value.shouldChangePassword,
        'storageLabel': value.storageLabel,
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

