/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PeopleUpdateItem } from './PeopleUpdateItem';
import {
    PeopleUpdateItemFromJSON,
    PeopleUpdateItemFromJSONTyped,
    PeopleUpdateItemToJSON,
} from './PeopleUpdateItem';

/**
 * 
 * @export
 * @interface PeopleUpdateDto
 */
export interface PeopleUpdateDto {
    /**
     * 
     * @type {Array<PeopleUpdateItem>}
     * @memberof PeopleUpdateDto
     */
    people: Array<PeopleUpdateItem>;
}

/**
 * Check if a given object implements the PeopleUpdateDto interface.
 */
export function instanceOfPeopleUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "people" in value;

    return isInstance;
}

export function PeopleUpdateDtoFromJSON(json: any): PeopleUpdateDto {
    return PeopleUpdateDtoFromJSONTyped(json, false);
}

export function PeopleUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeopleUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'people': ((json['people'] as Array<any>).map(PeopleUpdateItemFromJSON)),
    };
}

export function PeopleUpdateDtoToJSON(value?: PeopleUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'people': ((value.people as Array<any>).map(PeopleUpdateItemToJSON)),
    };
}

