/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueStatusDto
 */
export interface QueueStatusDto {
    /**
     * 
     * @type {boolean}
     * @memberof QueueStatusDto
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QueueStatusDto
     */
    isPaused: boolean;
}

/**
 * Check if a given object implements the QueueStatusDto interface.
 */
export function instanceOfQueueStatusDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "isPaused" in value;

    return isInstance;
}

export function QueueStatusDtoFromJSON(json: any): QueueStatusDto {
    return QueueStatusDtoFromJSONTyped(json, false);
}

export function QueueStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isActive': json['isActive'],
        'isPaused': json['isPaused'],
    };
}

export function QueueStatusDtoToJSON(value?: QueueStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isActive': value.isActive,
        'isPaused': value.isPaused,
    };
}

