/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemConfigLibraryScanDto } from './SystemConfigLibraryScanDto';
import {
    SystemConfigLibraryScanDtoFromJSON,
    SystemConfigLibraryScanDtoFromJSONTyped,
    SystemConfigLibraryScanDtoToJSON,
} from './SystemConfigLibraryScanDto';
import type { SystemConfigLibraryWatchDto } from './SystemConfigLibraryWatchDto';
import {
    SystemConfigLibraryWatchDtoFromJSON,
    SystemConfigLibraryWatchDtoFromJSONTyped,
    SystemConfigLibraryWatchDtoToJSON,
} from './SystemConfigLibraryWatchDto';

/**
 * 
 * @export
 * @interface SystemConfigLibraryDto
 */
export interface SystemConfigLibraryDto {
    /**
     * 
     * @type {SystemConfigLibraryScanDto}
     * @memberof SystemConfigLibraryDto
     */
    scan: SystemConfigLibraryScanDto;
    /**
     * 
     * @type {SystemConfigLibraryWatchDto}
     * @memberof SystemConfigLibraryDto
     */
    watch: SystemConfigLibraryWatchDto;
}

/**
 * Check if a given object implements the SystemConfigLibraryDto interface.
 */
export function instanceOfSystemConfigLibraryDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scan" in value;
    isInstance = isInstance && "watch" in value;

    return isInstance;
}

export function SystemConfigLibraryDtoFromJSON(json: any): SystemConfigLibraryDto {
    return SystemConfigLibraryDtoFromJSONTyped(json, false);
}

export function SystemConfigLibraryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemConfigLibraryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scan': SystemConfigLibraryScanDtoFromJSON(json['scan']),
        'watch': SystemConfigLibraryWatchDtoFromJSON(json['watch']),
    };
}

export function SystemConfigLibraryDtoToJSON(value?: SystemConfigLibraryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scan': SystemConfigLibraryScanDtoToJSON(value.scan),
        'watch': SystemConfigLibraryWatchDtoToJSON(value.watch),
    };
}

