/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Colorspace } from './Colorspace';
import {
    ColorspaceFromJSON,
    ColorspaceFromJSONTyped,
    ColorspaceToJSON,
} from './Colorspace';

/**
 * 
 * @export
 * @interface SystemConfigThumbnailDto
 */
export interface SystemConfigThumbnailDto {
    /**
     * 
     * @type {Colorspace}
     * @memberof SystemConfigThumbnailDto
     */
    colorspace: Colorspace;
    /**
     * 
     * @type {number}
     * @memberof SystemConfigThumbnailDto
     */
    jpegSize: number;
    /**
     * 
     * @type {number}
     * @memberof SystemConfigThumbnailDto
     */
    quality: number;
    /**
     * 
     * @type {number}
     * @memberof SystemConfigThumbnailDto
     */
    webpSize: number;
}

/**
 * Check if a given object implements the SystemConfigThumbnailDto interface.
 */
export function instanceOfSystemConfigThumbnailDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "colorspace" in value;
    isInstance = isInstance && "jpegSize" in value;
    isInstance = isInstance && "quality" in value;
    isInstance = isInstance && "webpSize" in value;

    return isInstance;
}

export function SystemConfigThumbnailDtoFromJSON(json: any): SystemConfigThumbnailDto {
    return SystemConfigThumbnailDtoFromJSONTyped(json, false);
}

export function SystemConfigThumbnailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemConfigThumbnailDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'colorspace': ColorspaceFromJSON(json['colorspace']),
        'jpegSize': json['jpegSize'],
        'quality': json['quality'],
        'webpSize': json['webpSize'],
    };
}

export function SystemConfigThumbnailDtoToJSON(value?: SystemConfigThumbnailDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'colorspace': ColorspaceToJSON(value.colorspace),
        'jpegSize': value.jpegSize,
        'quality': value.quality,
        'webpSize': value.webpSize,
    };
}

