/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemConfigFFmpegDto } from './SystemConfigFFmpegDto';
import {
    SystemConfigFFmpegDtoFromJSON,
    SystemConfigFFmpegDtoFromJSONTyped,
    SystemConfigFFmpegDtoToJSON,
} from './SystemConfigFFmpegDto';
import type { SystemConfigJobDto } from './SystemConfigJobDto';
import {
    SystemConfigJobDtoFromJSON,
    SystemConfigJobDtoFromJSONTyped,
    SystemConfigJobDtoToJSON,
} from './SystemConfigJobDto';
import type { SystemConfigLibraryDto } from './SystemConfigLibraryDto';
import {
    SystemConfigLibraryDtoFromJSON,
    SystemConfigLibraryDtoFromJSONTyped,
    SystemConfigLibraryDtoToJSON,
} from './SystemConfigLibraryDto';
import type { SystemConfigLoggingDto } from './SystemConfigLoggingDto';
import {
    SystemConfigLoggingDtoFromJSON,
    SystemConfigLoggingDtoFromJSONTyped,
    SystemConfigLoggingDtoToJSON,
} from './SystemConfigLoggingDto';
import type { SystemConfigMachineLearningDto } from './SystemConfigMachineLearningDto';
import {
    SystemConfigMachineLearningDtoFromJSON,
    SystemConfigMachineLearningDtoFromJSONTyped,
    SystemConfigMachineLearningDtoToJSON,
} from './SystemConfigMachineLearningDto';
import type { SystemConfigMapDto } from './SystemConfigMapDto';
import {
    SystemConfigMapDtoFromJSON,
    SystemConfigMapDtoFromJSONTyped,
    SystemConfigMapDtoToJSON,
} from './SystemConfigMapDto';
import type { SystemConfigNewVersionCheckDto } from './SystemConfigNewVersionCheckDto';
import {
    SystemConfigNewVersionCheckDtoFromJSON,
    SystemConfigNewVersionCheckDtoFromJSONTyped,
    SystemConfigNewVersionCheckDtoToJSON,
} from './SystemConfigNewVersionCheckDto';
import type { SystemConfigOAuthDto } from './SystemConfigOAuthDto';
import {
    SystemConfigOAuthDtoFromJSON,
    SystemConfigOAuthDtoFromJSONTyped,
    SystemConfigOAuthDtoToJSON,
} from './SystemConfigOAuthDto';
import type { SystemConfigPasswordLoginDto } from './SystemConfigPasswordLoginDto';
import {
    SystemConfigPasswordLoginDtoFromJSON,
    SystemConfigPasswordLoginDtoFromJSONTyped,
    SystemConfigPasswordLoginDtoToJSON,
} from './SystemConfigPasswordLoginDto';
import type { SystemConfigReverseGeocodingDto } from './SystemConfigReverseGeocodingDto';
import {
    SystemConfigReverseGeocodingDtoFromJSON,
    SystemConfigReverseGeocodingDtoFromJSONTyped,
    SystemConfigReverseGeocodingDtoToJSON,
} from './SystemConfigReverseGeocodingDto';
import type { SystemConfigServerDto } from './SystemConfigServerDto';
import {
    SystemConfigServerDtoFromJSON,
    SystemConfigServerDtoFromJSONTyped,
    SystemConfigServerDtoToJSON,
} from './SystemConfigServerDto';
import type { SystemConfigStorageTemplateDto } from './SystemConfigStorageTemplateDto';
import {
    SystemConfigStorageTemplateDtoFromJSON,
    SystemConfigStorageTemplateDtoFromJSONTyped,
    SystemConfigStorageTemplateDtoToJSON,
} from './SystemConfigStorageTemplateDto';
import type { SystemConfigThemeDto } from './SystemConfigThemeDto';
import {
    SystemConfigThemeDtoFromJSON,
    SystemConfigThemeDtoFromJSONTyped,
    SystemConfigThemeDtoToJSON,
} from './SystemConfigThemeDto';
import type { SystemConfigThumbnailDto } from './SystemConfigThumbnailDto';
import {
    SystemConfigThumbnailDtoFromJSON,
    SystemConfigThumbnailDtoFromJSONTyped,
    SystemConfigThumbnailDtoToJSON,
} from './SystemConfigThumbnailDto';
import type { SystemConfigTrashDto } from './SystemConfigTrashDto';
import {
    SystemConfigTrashDtoFromJSON,
    SystemConfigTrashDtoFromJSONTyped,
    SystemConfigTrashDtoToJSON,
} from './SystemConfigTrashDto';

/**
 * 
 * @export
 * @interface SystemConfigDto
 */
export interface SystemConfigDto {
    /**
     * 
     * @type {SystemConfigFFmpegDto}
     * @memberof SystemConfigDto
     */
    ffmpeg: SystemConfigFFmpegDto;
    /**
     * 
     * @type {SystemConfigJobDto}
     * @memberof SystemConfigDto
     */
    job: SystemConfigJobDto;
    /**
     * 
     * @type {SystemConfigLibraryDto}
     * @memberof SystemConfigDto
     */
    library: SystemConfigLibraryDto;
    /**
     * 
     * @type {SystemConfigLoggingDto}
     * @memberof SystemConfigDto
     */
    logging: SystemConfigLoggingDto;
    /**
     * 
     * @type {SystemConfigMachineLearningDto}
     * @memberof SystemConfigDto
     */
    machineLearning: SystemConfigMachineLearningDto;
    /**
     * 
     * @type {SystemConfigMapDto}
     * @memberof SystemConfigDto
     */
    map: SystemConfigMapDto;
    /**
     * 
     * @type {SystemConfigNewVersionCheckDto}
     * @memberof SystemConfigDto
     */
    newVersionCheck: SystemConfigNewVersionCheckDto;
    /**
     * 
     * @type {SystemConfigOAuthDto}
     * @memberof SystemConfigDto
     */
    oauth: SystemConfigOAuthDto;
    /**
     * 
     * @type {SystemConfigPasswordLoginDto}
     * @memberof SystemConfigDto
     */
    passwordLogin: SystemConfigPasswordLoginDto;
    /**
     * 
     * @type {SystemConfigReverseGeocodingDto}
     * @memberof SystemConfigDto
     */
    reverseGeocoding: SystemConfigReverseGeocodingDto;
    /**
     * 
     * @type {SystemConfigServerDto}
     * @memberof SystemConfigDto
     */
    server: SystemConfigServerDto;
    /**
     * 
     * @type {SystemConfigStorageTemplateDto}
     * @memberof SystemConfigDto
     */
    storageTemplate: SystemConfigStorageTemplateDto;
    /**
     * 
     * @type {SystemConfigThemeDto}
     * @memberof SystemConfigDto
     */
    theme: SystemConfigThemeDto;
    /**
     * 
     * @type {SystemConfigThumbnailDto}
     * @memberof SystemConfigDto
     */
    thumbnail: SystemConfigThumbnailDto;
    /**
     * 
     * @type {SystemConfigTrashDto}
     * @memberof SystemConfigDto
     */
    trash: SystemConfigTrashDto;
}

/**
 * Check if a given object implements the SystemConfigDto interface.
 */
export function instanceOfSystemConfigDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ffmpeg" in value;
    isInstance = isInstance && "job" in value;
    isInstance = isInstance && "library" in value;
    isInstance = isInstance && "logging" in value;
    isInstance = isInstance && "machineLearning" in value;
    isInstance = isInstance && "map" in value;
    isInstance = isInstance && "newVersionCheck" in value;
    isInstance = isInstance && "oauth" in value;
    isInstance = isInstance && "passwordLogin" in value;
    isInstance = isInstance && "reverseGeocoding" in value;
    isInstance = isInstance && "server" in value;
    isInstance = isInstance && "storageTemplate" in value;
    isInstance = isInstance && "theme" in value;
    isInstance = isInstance && "thumbnail" in value;
    isInstance = isInstance && "trash" in value;

    return isInstance;
}

export function SystemConfigDtoFromJSON(json: any): SystemConfigDto {
    return SystemConfigDtoFromJSONTyped(json, false);
}

export function SystemConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemConfigDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ffmpeg': SystemConfigFFmpegDtoFromJSON(json['ffmpeg']),
        'job': SystemConfigJobDtoFromJSON(json['job']),
        'library': SystemConfigLibraryDtoFromJSON(json['library']),
        'logging': SystemConfigLoggingDtoFromJSON(json['logging']),
        'machineLearning': SystemConfigMachineLearningDtoFromJSON(json['machineLearning']),
        'map': SystemConfigMapDtoFromJSON(json['map']),
        'newVersionCheck': SystemConfigNewVersionCheckDtoFromJSON(json['newVersionCheck']),
        'oauth': SystemConfigOAuthDtoFromJSON(json['oauth']),
        'passwordLogin': SystemConfigPasswordLoginDtoFromJSON(json['passwordLogin']),
        'reverseGeocoding': SystemConfigReverseGeocodingDtoFromJSON(json['reverseGeocoding']),
        'server': SystemConfigServerDtoFromJSON(json['server']),
        'storageTemplate': SystemConfigStorageTemplateDtoFromJSON(json['storageTemplate']),
        'theme': SystemConfigThemeDtoFromJSON(json['theme']),
        'thumbnail': SystemConfigThumbnailDtoFromJSON(json['thumbnail']),
        'trash': SystemConfigTrashDtoFromJSON(json['trash']),
    };
}

export function SystemConfigDtoToJSON(value?: SystemConfigDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ffmpeg': SystemConfigFFmpegDtoToJSON(value.ffmpeg),
        'job': SystemConfigJobDtoToJSON(value.job),
        'library': SystemConfigLibraryDtoToJSON(value.library),
        'logging': SystemConfigLoggingDtoToJSON(value.logging),
        'machineLearning': SystemConfigMachineLearningDtoToJSON(value.machineLearning),
        'map': SystemConfigMapDtoToJSON(value.map),
        'newVersionCheck': SystemConfigNewVersionCheckDtoToJSON(value.newVersionCheck),
        'oauth': SystemConfigOAuthDtoToJSON(value.oauth),
        'passwordLogin': SystemConfigPasswordLoginDtoToJSON(value.passwordLogin),
        'reverseGeocoding': SystemConfigReverseGeocodingDtoToJSON(value.reverseGeocoding),
        'server': SystemConfigServerDtoToJSON(value.server),
        'storageTemplate': SystemConfigStorageTemplateDtoToJSON(value.storageTemplate),
        'theme': SystemConfigThemeDtoToJSON(value.theme),
        'thumbnail': SystemConfigThumbnailDtoToJSON(value.thumbnail),
        'trash': SystemConfigTrashDtoToJSON(value.trash),
    };
}

