/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.94.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageByUserDto
 */
export interface UsageByUserDto {
    /**
     * 
     * @type {number}
     * @memberof UsageByUserDto
     */
    photos: number;
    /**
     * 
     * @type {number}
     * @memberof UsageByUserDto
     */
    quotaSizeInBytes: number | null;
    /**
     * 
     * @type {number}
     * @memberof UsageByUserDto
     */
    usage: number;
    /**
     * 
     * @type {string}
     * @memberof UsageByUserDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UsageByUserDto
     */
    userName: string;
    /**
     * 
     * @type {number}
     * @memberof UsageByUserDto
     */
    videos: number;
}

/**
 * Check if a given object implements the UsageByUserDto interface.
 */
export function instanceOfUsageByUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "photos" in value;
    isInstance = isInstance && "quotaSizeInBytes" in value;
    isInstance = isInstance && "usage" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "videos" in value;

    return isInstance;
}

export function UsageByUserDtoFromJSON(json: any): UsageByUserDto {
    return UsageByUserDtoFromJSONTyped(json, false);
}

export function UsageByUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageByUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'photos': json['photos'],
        'quotaSizeInBytes': json['quotaSizeInBytes'],
        'usage': json['usage'],
        'userId': json['userId'],
        'userName': json['userName'],
        'videos': json['videos'],
    };
}

export function UsageByUserDtoToJSON(value?: UsageByUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'photos': value.photos,
        'quotaSizeInBytes': value.quotaSizeInBytes,
        'usage': value.usage,
        'userId': value.userId,
        'userName': value.userName,
        'videos': value.videos,
    };
}

