/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerVersionReponseDto
 */
export interface ServerVersionReponseDto {
    /**
     * 
     * @type {number}
     * @memberof ServerVersionReponseDto
     */
    major: number;
    /**
     * 
     * @type {number}
     * @memberof ServerVersionReponseDto
     */
    minor: number;
    /**
     * 
     * @type {number}
     * @memberof ServerVersionReponseDto
     */
    patch: number;
    /**
     * 
     * @type {number}
     * @memberof ServerVersionReponseDto
     */
    build: number;
}

/**
 * Check if a given object implements the ServerVersionReponseDto interface.
 */
export function instanceOfServerVersionReponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "major" in value;
    isInstance = isInstance && "minor" in value;
    isInstance = isInstance && "patch" in value;
    isInstance = isInstance && "build" in value;

    return isInstance;
}

export function ServerVersionReponseDtoFromJSON(json: any): ServerVersionReponseDto {
    return ServerVersionReponseDtoFromJSONTyped(json, false);
}

export function ServerVersionReponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerVersionReponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'major': json['major'],
        'minor': json['minor'],
        'patch': json['patch'],
        'build': json['build'],
    };
}

export function ServerVersionReponseDtoToJSON(value?: ServerVersionReponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'major': value.major,
        'minor': value.minor,
        'patch': value.patch,
        'build': value.build,
    };
}

