#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${REPLICATION_USERNAME} WITH REPLICATION LOGIN PASSWORD '${REPLICATION_PASSWORD}';
EOSQL
