export enum JobName {
  ASSET_UPLOADED = 'asset-uploaded',
  MP4_CONVERSION = 'mp4-conversion',
  GENERATE_JPEG_THUMBNAIL = 'generate-jpeg-thumbnail',
  GENERATE_WEBP_THUMBNAIL = 'generate-webp-thumbnail',
  EXIF_EXTRACTION = 'exif-extraction',
  EXTRACT_VIDEO_METADATA = 'extract-video-metadata',
  REVERSE_GEOCODING = 'reverse-geocoding',
  USER_DELETION = 'user-deletion',
  TEMPLATE_MIGRATION = 'template-migration',
  CONFIG_CHANGE = 'config-change',
  OBJECT_DETECTION = 'detect-object',
  IMAGE_TAGGING = 'tag-image',
  DELETE_FILE_ON_DISK = 'delete-file-on-disk',
}
