// AUTO-GENERATED FILE, DO NOT MODIFY!
//
part of openapi.api;

/// List of permissions
enum Permission {
  all._(r'all'),
  activityCreate._(r'activity.create'),
  activityRead._(r'activity.read'),
  activityUpdate._(r'activity.update'),
  activityDelete._(r'activity.delete'),
  activityStatistics._(r'activity.statistics'),
  apiKeyCreate._(r'apiKey.create'),
  apiKeyRead._(r'apiKey.read'),
  apiKeyUpdate._(r'apiKey.update'),
  apiKeyDelete._(r'apiKey.delete'),
  assetRead._(r'asset.read'),
  assetUpdate._(r'asset.update'),
  assetDelete._(r'asset.delete'),
  assetStatistics._(r'asset.statistics'),
  assetShare._(r'asset.share'),
  assetView._(r'asset.view'),
  assetDownload._(r'asset.download'),
  assetUpload._(r'asset.upload'),
  assetCopy._(r'asset.copy'),
  assetDerive._(r'asset.derive'),
  assetEditGet._(r'asset.edit.get'),
  assetEditCreate._(r'asset.edit.create'),
  assetEditDelete._(r'asset.edit.delete'),
  albumCreate._(r'album.create'),
  albumRead._(r'album.read'),
  albumUpdate._(r'album.update'),
  albumDelete._(r'album.delete'),
  albumStatistics._(r'album.statistics'),
  albumShare._(r'album.share'),
  albumDownload._(r'album.download'),
  albumAssetCreate._(r'albumAsset.create'),
  albumAssetDelete._(r'albumAsset.delete'),
  albumUserCreate._(r'albumUser.create'),
  albumUserUpdate._(r'albumUser.update'),
  albumUserDelete._(r'albumUser.delete'),
  authChangePassword._(r'auth.changePassword'),
  authDeviceDelete._(r'authDevice.delete'),
  archiveRead._(r'archive.read'),
  backupList._(r'backup.list'),
  backupDownload._(r'backup.download'),
  backupUpload._(r'backup.upload'),
  backupDelete._(r'backup.delete'),
  duplicateRead._(r'duplicate.read'),
  duplicateDelete._(r'duplicate.delete'),
  faceCreate._(r'face.create'),
  faceRead._(r'face.read'),
  faceUpdate._(r'face.update'),
  faceDelete._(r'face.delete'),
  folderRead._(r'folder.read'),
  jobCreate._(r'job.create'),
  jobRead._(r'job.read'),
  libraryCreate._(r'library.create'),
  libraryRead._(r'library.read'),
  libraryUpdate._(r'library.update'),
  libraryDelete._(r'library.delete'),
  libraryStatistics._(r'library.statistics'),
  timelineRead._(r'timeline.read'),
  timelineDownload._(r'timeline.download'),
  maintenance._(r'maintenance'),
  mapRead._(r'map.read'),
  mapSearch._(r'map.search'),
  memoryCreate._(r'memory.create'),
  memoryRead._(r'memory.read'),
  memoryUpdate._(r'memory.update'),
  memoryDelete._(r'memory.delete'),
  memoryStatistics._(r'memory.statistics'),
  memoryAssetCreate._(r'memoryAsset.create'),
  memoryAssetDelete._(r'memoryAsset.delete'),
  notificationCreate._(r'notification.create'),
  notificationRead._(r'notification.read'),
  notificationUpdate._(r'notification.update'),
  notificationDelete._(r'notification.delete'),
  partnerCreate._(r'partner.create'),
  partnerRead._(r'partner.read'),
  partnerUpdate._(r'partner.update'),
  partnerDelete._(r'partner.delete'),
  personCreate._(r'person.create'),
  personRead._(r'person.read'),
  personUpdate._(r'person.update'),
  personDelete._(r'person.delete'),
  personStatistics._(r'person.statistics'),
  personMerge._(r'person.merge'),
  personReassign._(r'person.reassign'),
  pinCodeCreate._(r'pinCode.create'),
  pinCodeUpdate._(r'pinCode.update'),
  pinCodeDelete._(r'pinCode.delete'),
  pluginCreate._(r'plugin.create'),
  pluginRead._(r'plugin.read'),
  pluginUpdate._(r'plugin.update'),
  pluginDelete._(r'plugin.delete'),
  serverAbout._(r'server.about'),
  serverApkLinks._(r'server.apkLinks'),
  serverStorage._(r'server.storage'),
  serverStatistics._(r'server.statistics'),
  serverVersionCheck._(r'server.versionCheck'),
  serverLicenseRead._(r'serverLicense.read'),
  serverLicenseUpdate._(r'serverLicense.update'),
  serverLicenseDelete._(r'serverLicense.delete'),
  sessionCreate._(r'session.create'),
  sessionRead._(r'session.read'),
  sessionUpdate._(r'session.update'),
  sessionDelete._(r'session.delete'),
  sessionLock._(r'session.lock'),
  sharedLinkCreate._(r'sharedLink.create'),
  sharedLinkRead._(r'sharedLink.read'),
  sharedLinkUpdate._(r'sharedLink.update'),
  sharedLinkDelete._(r'sharedLink.delete'),
  stackCreate._(r'stack.create'),
  stackRead._(r'stack.read'),
  stackUpdate._(r'stack.update'),
  stackDelete._(r'stack.delete'),
  syncStream._(r'sync.stream'),
  syncCheckpointRead._(r'syncCheckpoint.read'),
  syncCheckpointUpdate._(r'syncCheckpoint.update'),
  syncCheckpointDelete._(r'syncCheckpoint.delete'),
  systemConfigRead._(r'systemConfig.read'),
  systemConfigUpdate._(r'systemConfig.update'),
  systemMetadataRead._(r'systemMetadata.read'),
  systemMetadataUpdate._(r'systemMetadata.update'),
  tagCreate._(r'tag.create'),
  tagRead._(r'tag.read'),
  tagUpdate._(r'tag.update'),
  tagDelete._(r'tag.delete'),
  tagAsset._(r'tag.asset'),
  userRead._(r'user.read'),
  userUpdate._(r'user.update'),
  userLicenseCreate._(r'userLicense.create'),
  userLicenseRead._(r'userLicense.read'),
  userLicenseUpdate._(r'userLicense.update'),
  userLicenseDelete._(r'userLicense.delete'),
  userOnboardingRead._(r'userOnboarding.read'),
  userOnboardingUpdate._(r'userOnboarding.update'),
  userOnboardingDelete._(r'userOnboarding.delete'),
  userPreferenceRead._(r'userPreference.read'),
  userPreferenceUpdate._(r'userPreference.update'),
  userProfileImageCreate._(r'userProfileImage.create'),
  userProfileImageRead._(r'userProfileImage.read'),
  userProfileImageUpdate._(r'userProfileImage.update'),
  userProfileImageDelete._(r'userProfileImage.delete'),
  queueRead._(r'queue.read'),
  queueUpdate._(r'queue.update'),
  queueJobCreate._(r'queueJob.create'),
  queueJobRead._(r'queueJob.read'),
  queueJobUpdate._(r'queueJob.update'),
  queueJobDelete._(r'queueJob.delete'),
  workflowCreate._(r'workflow.create'),
  workflowRead._(r'workflow.read'),
  workflowUpdate._(r'workflow.update'),
  workflowDelete._(r'workflow.delete'),
  adminUserCreate._(r'adminUser.create'),
  adminUserRead._(r'adminUser.read'),
  adminUserUpdate._(r'adminUser.update'),
  adminUserDelete._(r'adminUser.delete'),
  adminSessionRead._(r'adminSession.read'),
  adminAuthUnlinkAll._(r'adminAuth.unlinkAll'),

  /// Reserved for values from newer servers. Never sent by this client.
  valueUnknown._(r'__unknown__');

  const Permission._(this.value);

  final String value;

  static Permission? fromJson(dynamic value) {
    for (final e in values) {
      if (e.value == value) return e;
    }
    return value == null ? null : valueUnknown;
  }

  Object toJson() => value;

  @override
  String toString() => value.toString();
}
