experimental_monorepo_root = true

[monorepo]
config_roots = [
  "plugins",
  "server",
  "cli",
  "deployment",
  "mobile",
  "e2e",
  "web",
  "docs",
  ".github",
]

[tools]
node = "24.14.1"
flutter = { version = "3.38.10", platforms = { linux-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version }}-stable.tar.xz" }, macos-arm64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_{{ version }}-stable.zip" }, macos-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_{{ version }}-stable.zip" }, windows-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_{{ version }}-stable.zip" } }, version_expr = 'fromJSON(body).releases | filter({ #.channel == "stable" }) | map({ replace(#.version, "-stable", "") }) | sortVersions()', version_list_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json" }
pnpm = "10.32.1"
terragrunt = "0.99.5"
opentofu = "1.11.5"
java = "21.0.2"
dart = { version = "3.10.9", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-{{ os() }}-{{ arch() }}-release.zip", version_expr = 'fromJSON(body).prefixes | filter({ # matches "^channels/stable/release/(\\d+\\.\\d+\\.\\d+)/$" }) | map({split(#, "/")[3]}) | sortVersions()', version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/" }

[tools."github:CQLabs/homebrew-dcm"]
version = "1.35.1"
bin = "dcm"
postinstall = "chmod +x $MISE_TOOL_INSTALL_PATH/dcm"

[settings]
experimental = true
pin = true

# SDK tasks
[tasks."sdk:install"]
dir = "open-api/typescript-sdk"
run = "pnpm install --filter @immich/sdk --frozen-lockfile"

[tasks."sdk:build"]
dir = "open-api/typescript-sdk"
run = "pnpm run build"

# i18n tasks
[tasks."i18n:format"]
dir = "i18n"
run = "pnpm run format"

[tasks."i18n:format-fix"]
dir = "i18n"
run = "pnpm run format:fix"
