experimental_monorepo_root = true

[monorepo]
config_roots = [
  "plugins",
  "server",
  "cli",
  "deployment",
  "mobile",
  "e2e",
  "web",
  "docs",
  ".github",
  "machine-learning",
]

[tools]
node = "24.15.0"
flutter = "3.41.9"
pnpm = "10.33.1"
terragrunt = "1.0.3"
opentofu = "1.11.6"
java = "21.0.2"

[tools."github:CQLabs/homebrew-dcm"]
version = "1.37.0"
bin = "dcm"
postinstall = "chmod +x $MISE_TOOL_INSTALL_PATH/dcm"

[tools."github:jellyfin/jellyfin-ffmpeg"]
version = "7.1.3-6"

[tools."github:jellyfin/jellyfin-ffmpeg".platforms]
linux-x64 = { asset_pattern = "jellyfin-ffmpeg_*_portable_linux64-gpl.tar.xz" }
linux-arm64 = { asset_pattern = "jellyfin-ffmpeg_*_portable_linuxarm64-gpl.tar.xz" }
macos-x64 = { asset_pattern = "jellyfin-ffmpeg_*_portable_mac64-gpl.tar.xz" }
macos-arm64 = { asset_pattern = "jellyfin-ffmpeg_*_portable_macarm64-gpl.tar.xz" }

[settings]
experimental = true
pin = true

# SDK tasks
[tasks."sdk:install"]
dir = "open-api/typescript-sdk"
run = "pnpm install --filter @immich/sdk --frozen-lockfile"

[tasks."sdk:build"]
dir = "open-api/typescript-sdk"
run = "pnpm run build"

# i18n tasks
[tasks."i18n:format"]
dir = "i18n"
run = "pnpm run format"

[tasks."i18n:format-fix"]
dir = "i18n"
run = "pnpm run format:fix"
