packages:
  - cli
  - docs
  - e2e
  - e2e-auth-server
  - i18n
  - open-api/typescript-sdk
  - server
  - plugins
  - tools/upstream-preflight
  - web
  - .github
dedupePeerDependents: false
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - canvas
  - core-js
  - core-js-pure
  - cpu-features
  - es5-ext
  - esbuild
  - msgpackr-extract
  - postman-code-generators
  - protobufjs
  - ssh2
  - utimes
injectWorkspacePackages: true
onlyBuiltDependencies:
  - sharp
  - '@tailwindcss/oxide'
  - bcrypt
overrides:
  canvas: 2.11.2
  sharp: ^0.34.5
packageExtensions:
  '@immich/ui':
    dependencies:
      tailwindcss: '>=4.1'
  '@photo-sphere-viewer/equirectangular-video-adapter':
    dependencies:
      three: '*'
  '@photo-sphere-viewer/video-plugin':
    dependencies:
      three: '*'
  bcrypt:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  nestjs-kysely:
    dependencies:
      tslib: '*'
  nestjs-otel:
    dependencies:
      tslib: '*'
  sharp:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  tailwind-variants:
    dependencies:
      tailwindcss: '>=4.1'
patchedDependencies:
  '@immich/ui@0.76.2': patches/@immich__ui@0.76.2.patch
preferWorkspacePackages: true
shamefullyHoist: false
verifyDepsBeforeRun: install
