packages:
  - cli
  - docs
  - e2e
  - open-api/typescript-sdk
  - server
  - web
  - .github

dedupePeerDependents: false

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - canvas
  - core-js
  - core-js-pure
  - cpu-features
  - es5-ext
  - esbuild
  - msgpackr-extract
  - postman-code-generators
  - protobufjs
  - ssh2
  - utimes

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - sharp

overrides:
  canvas: 2.11.2
  sharp: ^0.34.4

packageExtensions:
  '@immich/ui':
    dependencies:
      tailwindcss: '>=4.1'
  '@photo-sphere-viewer/equirectangular-video-adapter':
    dependencies:
      three: '*'
  '@photo-sphere-viewer/video-plugin':
    dependencies:
      three: '*'
  nestjs-kysely:
    dependencies:
      tslib: '*'
  nestjs-otel:
    dependencies:
      tslib: '*'
  sharp:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  tailwind-variants:
    dependencies:
      tailwindcss: '>=4.1'

preferWorkspacePackages: true

shamefullyHoist: false

verifyDepsBeforeRun: install
