### GET request to example server
GET http://localhost:2283/api/playback/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3OTExNjE5LWZjMzctNGY2Yi1hMDMzLTExN2I0MTg4MjZmYyIsInBhdGgiOiJ1cGxvYWQvdXBsb2FkLzk1YWIzNjUwLTViMmYtNDViNC04YzU4LTAzZDgwZDY5OWNjZi84YS81Ni84YTU2MGNkYy0yYzUzLTQ3YjMtYjY3MC02NzFkZGFmNjUzYWMubXA0Iiwic2Vzc2lvbklkIjoiOU1GUXVYd2ZKcHA4M3JPTjR5cmNJdyIsImlhdCI6MTc1MjY2NjEzMn0.iK5KNFDrYNs6Jyx6YHMGz4pIQDHeDl6GkjA7YCD9-ds/h264/1080p.m3u8

###
