import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'package:analyzer/dart/element/type.dart';

import 'discovery.dart';
import 'member_selection.dart';
import 'type_renderer.dart';

/// Emits one zero-cost `extension type` handle per member over mockito's
/// generated mock classes.
///
/// Signatures come from the *interface* element, not from mockito's generated
/// override. That matters: mockito widens every non-nullable parameter to
/// nullable so its `Null get any` can be passed, and reading the generated file
/// would inherit that widening. `calledWith` only ever passes concrete values,
/// so it can declare the true types and hand them to the widened method — a
/// `List<String>` goes into a `List<String>?` parameter without complaint.
///
/// Nothing here registers fallback values or synthesises fakes: mockito's own
/// builder already bakes a default into every generated member and emits its own
/// `SmartFake`s, so a second layer of that would be redundant.
class Emitter {
  Emitter(this.types, {required this.mocksImport, required this.ownedPackages});

  final TypeRenderer types;

  /// Packages whose members get handles. See [selectMembers].
  final Set<String> ownedPackages;

  /// Relative import of mockito's generated mocks, whose classes are referenced
  /// unprefixed — every one is named `Mock…`, so collisions cannot arise.
  final String mocksImport;

  final List<SkippedMember> skipped = [];
  final _body = StringBuffer();
  var _handles = 0;
  var _facades = 0;

  /// Whether any handle emitted a `calledWithMatching`, the only user of `_w`.
  var _usesMatchers = false;

  int get handleCount => _handles;
  int get facadeCount => _facades;

  /// Emits every handle for [target], plus the facade that exposes them.
  ///
  /// A member the emitter cannot render is recorded in [skipped] rather than
  /// thrown, so one exotic signature degrades to a missing handle instead of
  /// failing a build that the whole test suite depends on.
  void emitTarget(MockTarget target) {
    final typeName = _uniqueTypeName(target.name);
    final accessors = <String, String>{};

    for (final member in selectMembers(target.element, ownedPackages: ownedPackages)) {
      if (member.typeParameters.isNotEmpty) {
        skipped.add(SkippedMember(member.name, '$typeName: generic member, `any` cannot be reified'));
        continue;
      }
      if (!_isIdentifier(member.name)) {
        skipped.add(SkippedMember(member.name, '$typeName: operator, which has no accessor spelling'));
        continue;
      }
      final accessor = _accessorFor(member, accessors.keys.toSet());
      final handle = '\$$typeName\$$accessor';
      try {
        _emitHandle(handle, target.mockClass, member);
      } on UnrenderableType catch (e) {
        skipped.add(SkippedMember(member.name, '$typeName: $e'));
        continue;
      }
      accessors[accessor] = handle;
      _handles++;
    }

    _emitFacade(target, typeName, accessors);
    _facades++;
  }

  String finish() {
    final out = StringBuffer()
      ..writeln('// GENERATED by package:mockito_handles — do not edit.')
      ..writeln('//')
      ..writeln('// Per-member stub/verify handles over mockito mocks. Signatures are the real')
      ..writeln('// interface signatures, so argument types are checked as declared.')
      ..writeln('// ignore_for_file: type=lint');

    // `_w` is only reachable from `calledWithMatching`, which only methods get.
    // A target of nothing but getters and setters would leave both the helper and
    // the matcher import unused, and `unused_element` is a warning that
    // `type=lint` does not silence.
    if (_usesMatchers) out.writeln("import 'package:matcher/matcher.dart' as _t;");
    out
      ..writeln("import 'package:mockito/mockito.dart' as _k;")
      ..writeln("import '$mocksImport';");
    for (final import in types.imports) {
      out.writeln("import '${import.key}' as ${import.value};");
    }
    out.writeln();
    if (_usesMatchers) {
      out
        ..writeln('/// `null` means "no constraint", so an omitted argument matches anything.')
        ..writeln('_t.Matcher _w(Object? v) => v == null ? _t.anything : _t.wrapMatcher(v);')
        ..writeln();
    }
    out.write(_body);
    return out.toString();
  }

  // ── handles ───────────────────────────────────────────────────────────────

  /// Names the facade declares itself. A member accessor colliding with one is a
  /// compile error, not a shadowing — a repository declaring `reset()` hits this.
  static const _reserved = {'mock', 'reset', 'zeroInteractions'};

  static final _identifier = RegExp(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$');

  final _typeNames = <String>{};

  /// The base for this target's facade and handle names.
  ///
  /// Every generated name keys off the interface's *simple* name, so two
  /// same-named types from different libraries — which mockito allows, and
  /// `MockSpec(as:)` exists to disambiguate on its side — would otherwise emit
  /// the same `$Name$member` twice and produce a file that does not compile.
  String _uniqueTypeName(String name) {
    if (_typeNames.add(name)) return name;
    for (var i = 2; ; i++) {
      if (_typeNames.add('$name$i')) return '$name$i';
    }
  }

  /// Operators are the only members whose name is not an identifier, and there
  /// is no spelling for them: neither `$Target$+` nor `_m.+(x)` is valid Dart.
  static bool _isIdentifier(String name) => _identifier.hasMatch(name);

  /// The facade getter for [m], unique within [taken].
  ///
  /// A setter's accessor is derived (`name` becomes `setName`), so it can land
  /// on a method that is literally called `setName`. Both would then emit
  /// `$Target$setName` and the generated file would not compile, so the derived
  /// name gives way to the declared one.
  String _accessorFor(SelectedMember m, Set<String> taken) {
    var base = m.kind == MemberKind.setter ? 'set${m.name[0].toUpperCase()}${m.name.substring(1)}' : m.name;
    if (_reserved.contains(base)) base = '${base}Member';
    if (!taken.contains(base)) return base;
    for (var i = 2; ; i++) {
      final candidate = '$base$i';
      if (!taken.contains(candidate)) return candidate;
    }
  }

  void _emitHandle(String handle, String mockClass, SelectedMember m) {
    // Render everything that can throw before writing a byte, so a failure
    // leaves no half-emitted handle behind.
    final parts = _Rendered(m, types);
    final not = '$handle\$Not';

    _body.writeln('extension type const $handle($mockClass _m) {');
    switch (m.kind) {
      case MemberKind.setter:
        _emitSetter(m, parts);
      case MemberKind.getter:
        // A getter is read, not called, so `anyInvoke` must not be used here —
        // it would emit `_m.name()` and try to invoke the returned value.
        _emitStubs(m, parts, '_m.${m.name}');
        _emitCounts('_m.${m.name}');
      case MemberKind.method:
        _usesMatchers = true;
        _emitStubs(m, parts, parts.anyInvoke(m));
        // Calling the handle calls the member. This is what `verifyInOrder`
        // needs — it takes the *results* of invoking the mock, not a description
        // of them — and it gives back the direct call that the handle's shadowing
        // of the member name would otherwise cost:
        //
        //     verifyInOrder([repo.assetsIn('a'), repo.markHashed(ids)]);
        _body.writeln('  ${parts.returnType} call(${parts.widenedParams}) => _m.${m.name}(${parts.passThrough});');
        _body.writeln(
          '  void calledWith(${parts.realParams}) => '
          '_k.verify(_m.${m.name}(${parts.passThrough}));',
        );
        _body.writeln(
          '  void calledWithMatching(${parts.matcherParams}) => '
          '_k.verify(_m.${m.name}(${parts.matcherArgs}));',
        );
        _emitCounts(parts.anyInvoke(m));
        _emitCapture(m, parts);
    }
    _body.writeln('  $not get not => $not(_m);');
    _body.writeln('}');
    _body.writeln();
    _emitNot(not, mockClass, m, parts);
  }

  /// The negated verifications, reached through `.not`.
  ///
  /// Every verification form has a negation and no stub does, which is why `not`
  /// is a separate type rather than a flag: `mockResolvedValue` cannot be
  /// meaningfully inverted, so it must not be reachable here. This mirrors jest,
  /// where `.not` sits on the `expect` side and never on `mockReturnValue`.
  ///
  /// A negation never carries `.called(n)` — `verifyNever` already asserts the
  /// count is zero, and mockito's `.called()` on a `verifyNever` would pass
  /// vacuously.
  void _emitNot(String name, String mockClass, SelectedMember m, _Rendered parts) {
    _body.writeln('/// Negated verifications for the member above: `handle.not.calledWith(x)`.');
    _body.writeln('extension type const $name($mockClass _m) {');
    switch (m.kind) {
      case MemberKind.setter:
        _body.writeln('  void calledWith(${_setterValue(parts)} value) => _k.verifyNever(_m.${m.name} = value);');
        _body.writeln('  void called() => _k.verifyNever(_m.${m.name} = _k.any);');
      case MemberKind.getter:
        _body.writeln('  void called() => _k.verifyNever(_m.${m.name});');
      case MemberKind.method:
        _body.writeln('  void calledWith(${parts.realParams}) => _k.verifyNever(_m.${m.name}(${parts.passThrough}));');
        _body.writeln(
          '  void calledWithMatching(${parts.matcherParams}) => '
          '_k.verifyNever(_m.${m.name}(${parts.matcherArgs}));',
        );
        _body.writeln('  void called() => _k.verifyNever(${parts.anyInvoke(m)});');
    }
    _body.writeln('}');
    _body.writeln();
  }

  static String _setterValue(_Rendered parts) => parts.paramTypes.isEmpty ? 'Object?' : parts.paramTypes.single;

  void _emitSetter(SelectedMember m, _Rendered parts) {
    _body.writeln('  void calledWith(${_setterValue(parts)} value) => _k.verify(_m.${m.name} = value);');
    _body.writeln('  List<dynamic> get captured => _k.verify(_m.${m.name} = _k.captureAny).captured;');
  }

  void _emitStubs(SelectedMember m, _Rendered parts, String invoke) {
    final value = parts.valueType;
    final isVoid = value == 'void';
    if (m.isAsync) {
      final future = parts.futureType;
      _body.writeln(
        isVoid
            ? '  void mockResolvedValue() => _k.when($invoke).thenAnswer((_) async {});'
            : '  void mockResolvedValue($value value) => _k.when($invoke).thenAnswer((_) async => value);',
      );
      // `thenThrow` throws synchronously, which is not what an async member
      // does. `Future.error` is targeted even for a `FutureOr` return, because
      // `FutureOr` has no `.error` constructor and a Future satisfies it anyway.
      _body.writeln(
        '  void mockRejectedValue(Object error) => '
        '_k.when($invoke).thenAnswer((_) => $future.error(error));',
      );
      // A `FutureOr<T>` member can legitimately return a bare `T`, and code that
      // branches on `result is T` versus `result is Future<T>` takes a different
      // path for each. Offering only `mockResolvedValue` would silently force the
      // async branch, so the synchronous form is emitted alongside it.
      if (!isVoid && m.isFutureOr) {
        _body.writeln('  void mockReturnValue($value value) => _k.when($invoke).thenAnswer((_) => value);');
      }
      _emitImplementation(m, parts, invoke, parts.returnType);
      return;
    }
    if (isVoid) {
      // `thenAnswer` rather than `thenReturn` throughout: mockito rejects
      // `thenReturn` for a Stream or Future return (mock.dart:629), and a
      // synchronous member can still return a Stream. `thenAnswer` is valid for
      // every type, so there is no case to special-case.
      _body.writeln('  void mockReturnValue() => _k.when($invoke).thenAnswer((_) => null);');
    } else {
      _body.writeln('  void mockReturnValue($value value) => _k.when($invoke).thenAnswer((_) => value);');
      _emitImplementation(m, parts, invoke, value);
    }
    _body.writeln('  void mockThrow(Object error) => _k.when($invoke).thenThrow(error);');
  }

  /// `mockImplementation` taking the member's **real arguments**, not an
  /// `Invocation`.
  ///
  /// This is the whole point of the callback form — an argument-dependent stub
  /// reads as ordinary Dart:
  ///
  /// ```dart
  /// repo.assetsIn.mockImplementation((albumId) async => byAlbum[albumId] ?? []);
  /// ```
  ///
  /// Handing over an `Invocation` instead would make every such stub unpack
  /// `positionalArguments[0] as T` by hand, which is the boilerplate these
  /// handles exist to delete.
  void _emitImplementation(SelectedMember m, _Rendered parts, String invoke, String value) {
    if (m.parameters.isEmpty) {
      _body.writeln('  void mockImplementation($value Function() fn) => _k.when($invoke).thenAnswer((_) => fn());');
      return;
    }
    _body.writeln(
      '  void mockImplementation($value Function(${parts.callbackParams}) fn) => '
      '_k.when($invoke).thenAnswer((i) => fn(${parts.unpackArgs}));',
    );
  }

  void _emitCounts(String invoke) {
    _body.writeln('  void calledOnce() => _k.verify($invoke).called(1);');
    _body.writeln('  void calledTimes(int n) => _k.verify($invoke).called(n);');
  }

  void _emitCapture(SelectedMember m, _Rendered parts) {
    if (m.parameters.isEmpty) return;
    _body.writeln('  List<dynamic> get captured => _k.verify(_m.${m.name}(${parts.captureArgs})).captured;');
    // mockito's `captured` is flat across every call, so grouping per call means
    // chunking by arity. Each chunk becomes a record named after the real
    // parameters: `calls.single.albumId` rather than `calls.single[0] as String`,
    // which is both typed and readable without opening this file to count.
    final record = parts.recordType;
    _body.writeln('  List<$record> get calls {');
    _body.writeln('    final flat = captured;');
    _body.writeln('    const arity = ${m.parameters.length};');
    _body.writeln('    return [for (var i = 0; i < flat.length; i += arity) ${parts.recordLiteral}];');
    _body.writeln('  }');
    _body.writeln('  $record get lastCall => calls.last;');
  }

  void _emitFacade(MockTarget target, String typeName, Map<String, String> accessors) {
    final name = '${typeName}Mock';
    final mockClass = target.mockClass;
    _body.writeln('/// Handles for every owned member of `${target.name}`.');
    _body.writeln('///');
    _body.writeln('/// `$name()` builds its own mock; `$name.of(existing)` wraps one.');
    _body.writeln('///');
    _body.writeln('/// Build one per test: a fresh mock has no stubs and no recorded calls, so');
    _body.writeln('/// there is nothing to reset. Under `@GenerateNiceMocks` an unstubbed member');
    _body.writeln('/// returns a default, so stub only what the test depends on; under');
    _body.writeln('/// `@GenerateMocks` it throws instead.');
    // `implements $mockClass` makes the facade a subtype of the mock, and so of
    // the interface the mock implements. Without it every use of the facade *as
    // a value* — a constructor argument, a provider override — needs `.mock`.
    //
    // A handle accessor shares its name with the member it wraps, and an
    // extension type's own members win over the ones it implements, so
    // `facade.foo` is the handle while `facade.mock.foo(…)` is still the call. A
    // member with no handle (an operator, a generic) stays reachable directly.
    _body.writeln('extension type const $name.of($mockClass mock) implements $mockClass {');
    _body.writeln('  $name() : this.of($mockClass());');
    accessors.forEach((accessor, handle) {
      _body.writeln('  $handle get $accessor => $handle(mock);');
    });
    _body.writeln('  void reset() => _k.reset(mock);');
    _body.writeln('  void zeroInteractions() => _k.verifyZeroInteractions(mock);');
    _body.writeln('}');
    _body.writeln();
  }
}

/// Every rendered fragment a handle needs, computed once so an
/// [UnrenderableType] surfaces before any output is written.
class _Rendered {
  _Rendered(SelectedMember m, TypeRenderer types)
    : returnType = types.render(m.returnType),
      valueType = _unwrap(m, types),
      futureType = _futureType(m, types),
      paramTypes = m.parameters.map((p) => types.render(p.type)).toList(),
      _params = _describe(m, types) {
    _positional = _params.where((p) => !p.element.isNamed).toList(growable: false);
    _named = _params.where((p) => p.element.isNamed).toList(growable: false);
  }

  /// Renders each parameter once, rather than per fragment that mentions it.
  ///
  /// A member with `p` parameters appears in a dozen emitted fragments, so
  /// resolving a parameter's type, default and safe name by searching the list
  /// each time made every member quadratic in its own arity.
  static List<_Param> _describe(SelectedMember m, TypeRenderer types) => [
    for (final (i, p) in m.parameters.indexed)
      _Param(p, types.render(p.type), _safeName(p, i))..defaultCode = _renderDefault(p, types),
  ];

  /// A name usable as an identifier in generated code.
  ///
  /// `void poke(int _)` and `void poke(int _x)` are both legal Dart, but `_` is a
  /// wildcard that cannot be referenced and `_x` cannot become a named
  /// parameter, which `calledWithMatching` needs it to be.
  static String _safeName(FormalParameterElement p, int index) {
    final name = p.name;
    return (name == null || name.isEmpty || name.startsWith('_')) ? 'p$index' : name;
  }

  final String returnType;

  /// The awaited type for an async member, the return type otherwise.
  final String valueType;

  /// `Future<T>` for an async member — the target of `.error(...)`.
  final String futureType;
  final List<String> paramTypes;
  final List<_Param> _params;
  late final List<_Param> _positional;
  late final List<_Param> _named;

  static String _unwrap(SelectedMember m, TypeRenderer types) {
    final t = m.returnType;
    if (m.isAsync && t is InterfaceType && t.typeArguments.length == 1) {
      return types.render(t.typeArguments.single);
    }
    return types.render(t);
  }

  static String _futureType(SelectedMember m, TypeRenderer types) {
    final t = m.returnType;
    if (!m.isAsync || t is! InterfaceType || t.typeArguments.length != 1) return 'Future<void>';
    return 'Future<${types.render(t.typeArguments.single)}>';
  }

  /// `defaultValueCode` is raw source from the *declaring* library, so it only
  /// survives being copied into the generated file if every name it mentions
  /// resolves there.
  ///
  /// Two shapes do: a literal (`false`, `0`, `const []`), and a reference rooted
  /// at the parameter's own type (`Duration.zero`, `const Option.none()`), whose
  /// leading type name is rewritten to its prefixed form.
  ///
  /// Everything else — a top-level constant, another class's static, an enum the
  /// parameter is not typed as — names something the generated file never
  /// imports, so it returns null and the parameter becomes `required`. Stating
  /// the argument is a small cost; emitting `kAnimDuration` into a file that has
  /// never heard of it is a build break.
  static String? _renderDefault(FormalParameterElement p, TypeRenderer types) {
    final code = p.defaultValueCode?.trim();
    if (code == null) return null;
    if (!_hasFreeIdentifier.hasMatch(code)) return code;

    final element = p.type.element;
    if (element is! InterfaceElement) return null;
    final name = element.name;
    if (name == null) return null;

    // Rooted at the parameter's own type, so the only name to rewrite is that
    // type's. `Durations.short1` and `kAnimDuration` both fail here, which is
    // the point: neither is `Duration`.
    if (!RegExp('^(const\\s+)?${RegExp.escape(name)}\\b').hasMatch(code)) return null;

    final String rendered;
    try {
      rendered = types.renderElement(element);
    } on UnrenderableType {
      return null;
    }
    return code.replaceFirst(RegExp('(?<![\\w.\$])${RegExp.escape(name)}(?![\\w\$])'), rendered);
  }

  /// A name the generated file would have to resolve on its own.
  ///
  /// Excludes anything after a `.`, which is a member access rather than a free
  /// reference — and in particular covers the dot shorthand `const .none()`,
  /// whose `none` resolves against the parameter type the emitter itself writes.
  static final _hasFreeIdentifier = RegExp(r'(?<![\w$.])(?!const\b|true\b|false\b|null\b)[a-zA-Z_$][\w$]*');

  /// `any` / `anyNamed` for every parameter — shared by stubbing and by the
  /// no-argument verify forms.
  String anyInvoke(SelectedMember m) {
    final args = [
      ..._positional.map((_) => '_k.any'),
      ..._named.map((p) => "${p.label}: _k.anyNamed('${p.label}')"),
    ].join(', ');
    return '_m.${m.name}($args)';
  }

  String get realParams {
    final named = _named
        .map((p) {
          if (p.defaultCode != null) return '${p.type} ${p.name} = ${p.defaultCode}';
          // `required` in the interface stays required. A default that could not be
          // rendered also becomes required, so the caller states it rather than
          // verifying against a value this generator guessed. An optional nullable
          // parameter needs neither: its implicit default is already `null`.
          if (p.element.isRequiredNamed || p.element.defaultValueCode != null) {
            return 'required ${p.type} ${p.name}';
          }
          return '${p.type} ${p.name}';
        })
        .join(', ');
    return [if (_positional.isNotEmpty) _positionalParams, if (named.isNotEmpty) '{$named}'].join(', ');
  }

  /// The positional list, preserving optionality.
  ///
  /// `count(String id, [bool deep = false])` must not become
  /// `calledWith(String id, bool deep)` — that would force every call site to
  /// state an argument the real API lets it omit. The bracket only opens when
  /// every remaining parameter can legally be omitted, since an optional
  /// positional with no default and a non-nullable type has nothing to fall back
  /// to but a value this generator would have invented.
  String get _positionalParams {
    final from = _positional.indexWhere((p) => p.element.isOptionalPositional);
    final optional = from >= 0 && _positional.skip(from).every((p) => p.defaultCode != null || p.isNullable)
        ? from
        : -1;

    final parts = [
      for (final (i, p) in _positional.indexed)
        '${i == optional ? '[' : ''}${p.type} ${p.name}'
            '${i >= optional && optional >= 0 && p.defaultCode != null ? ' = ${p.defaultCode}' : ''}',
    ];
    return optional < 0 ? parts.join(', ') : '${parts.join(', ')}]';
  }

  String get passThrough =>
      [..._positional.map((p) => p.name), ..._named.map((p) => '${p.label}: ${p.name}')].join(', ');

  /// Every parameter as an optional `Object?`, so any subset may be constrained.
  ///
  /// The name is the *safe* one: this turns positional parameters into named
  /// ones, and a positional may legally be called `_x`, which is not a legal
  /// named parameter.
  String get matcherParams => _params.isEmpty ? '' : '{${_params.map((p) => 'Object? ${p.name}').join(', ')}}';

  /// The callback's parameter list, mirroring the real signature.
  ///
  /// Named parameters are `required` because mockito's generated override always
  /// forwards every named argument into the `Invocation` — its own default fills
  /// in when the caller omits one — so the value is never actually absent.
  String get callbackParams {
    final positional = _positional.map((p) => '${p.type} ${p.name}').join(', ');
    final named = _named.map((p) => 'required ${p.type} ${p.name}').join(', ');
    return [if (positional.isNotEmpty) positional, if (named.isNotEmpty) '{$named}'].join(', ');
  }

  /// Unpacks the recorded [Invocation] back into typed arguments.
  String get unpackArgs => [
    for (final (i, p) in _positional.indexed) 'i.positionalArguments[$i] as ${p.type}',
    ..._named.map((p) => '${p.label}: i.namedArguments[#${p.label}] as ${p.type}'),
  ].join(', ');

  String get matcherArgs => [
    ..._positional.map((p) => '_k.argThat(_w(${p.name}))'),
    ..._named.map((p) => "${p.label}: _k.argThat(_w(${p.name}), named: '${p.label}')"),
  ].join(', ');

  /// The parameter list for `call`, widened to nullable like mockito's override.
  ///
  /// `call` exists to *be* `mock.member(...)`, so it has to accept everything
  /// that does — including `any` and `captureAny`, which are typed `Null`. Real
  /// values still fit, since a `T` is a `T?`.
  String get widenedParams {
    final positional = _positional.map((p) => '${_nullable(p.type)} ${p.name}').join(', ');
    final named = _named.map((p) => '${_nullable(p.type)} ${p.name}').join(', ');
    return [if (positional.isNotEmpty) positional, if (named.isNotEmpty) '{$named}'].join(', ');
  }

  static String _nullable(String type) => type.endsWith('?') || type == 'dynamic' ? type : '$type?';

  /// The captured arguments of one call, as a record named after the parameters.
  ///
  /// Field order follows [captureArgs] — positional first, then named in
  /// declaration order — because that is the order mockito appends them to its
  /// flat `captured` list.
  String get recordType => '({${_ordered.map((p) => '${p.type} ${p.name}').join(', ')}})';

  String get recordLiteral =>
      '(${_ordered.indexed.map((e) => '${e.$2.name}: flat[i + ${e.$1}] as ${e.$2.type}').join(', ')})';

  List<_Param> get _ordered => [..._positional, ..._named];

  String get captureArgs => [
    ..._positional.map((_) => '_k.captureAny'),
    ..._named.map((p) => "${p.label}: _k.captureAnyNamed('${p.label}')"),
  ].join(', ');
}

/// One parameter, rendered once.
///
/// [name] and [label] differ only for a positional parameter whose declared name
/// cannot be used as an identifier in generated code — `_`, or anything
/// `_`-prefixed, which would be a wildcard or an illegal private named
/// parameter. [label] is always the declared name, because a named argument must
/// match the interface; Dart forbids private named parameters, so the two can
/// only diverge where no label is needed.
class _Param {
  _Param(this.element, this.type, this.name);

  final FormalParameterElement element;
  final String type;
  final String name;

  String get label => element.name ?? name;
  bool get isNullable => element.type.nullabilitySuffix == NullabilitySuffix.question;
  String? defaultCode;
}
