# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart.dev/tools/linter-rules
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.

  rules:
    # Formatting
    avoid_print: true
    require_trailing_commas: true
    unrelated_type_equality_checks: true
    prefer_const_constructors: true
    always_use_package_imports: true
    always_put_control_body_on_new_line: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    prefer_final_locals: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
    directives_ordering: true
    no_leading_underscores_for_local_identifiers: true
    always_declare_return_types: true
    avoid_void_async: true
    noop_primitive_operations: true
    use_named_constants: true
    combinators_ordering: true
    avoid_multiple_declarations_per_line: true
    unnecessary_breaks: true

    # Correctness
    no_adjacent_strings_in_list: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    discarded_futures: true
    no_self_assignments: true
    throw_in_finally: true
    collection_methods_unrelated_type: true
    cast_nullable_to_non_nullable: true

    # Known issues
    avoid_slow_async_io: true
    avoid_type_to_string: true

    # Flutter specific
    use_build_context_synchronously: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
    avoid_unnecessary_containers: true
    use_full_hex_values_for_flutter_colors: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - generated/openapi/**
    - build/**
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.drift.dart

  # NOTE: We explicitly do not use riverpod_lint as there are analyzer version conflicts between
  # our Flutter version and the required old riverpod_lint 2.x
  errors:
    unawaited_futures: warning
    always_put_control_body_on_new_line: warning

dart_code_metrics:
  rules:
    - banned-usage:
        entries:
          - name: debugPrint
            description: Use dPrint instead of debugPrint for proper tree-shaking in release builds.
            exclude-paths:
              - 'lib/utils/debug_print.dart'
            severity: perf
    # All rules from "recommended" preset
    # Show potential errors
  #  - avoid-cascade-after-if-null
  #  - avoid-collection-methods-with-unrelated-types
  #  - avoid-duplicate-exports
  #  - avoid-dynamic
  #  - avoid-missing-enum-constant-in-map
  #  - avoid-passing-async-when-sync-expected
  #  - avoid-throw-in-catch-block
    - avoid-unused-parameters
    - prefer-const-border-radius
    - prefer-declaring-const-constructor
    - prefer-switch-expression

    # Riverpod
    - avoid-calling-notifier-members-inside-build
    - avoid-notifier-constructors
    - avoid-nullable-async-value-pattern
    - avoid-public-notifier-properties
    - avoid-ref-inside-state-dispose
    - avoid-ref-read-inside-build
    - avoid-ref-watch-outside-build
    - avoid-unnecessary-consumer-widgets
    - dispose-provided-instances
    - prefer-immutable-provider-arguments
    - use-ref-and-state-synchronously
    - use-ref-read-synchronously
