targets:
   $default:
     builders:
       #drift @DriftDatabase()
       drift_dev:
         # Disable default builder to use modular builder instead
         enabled: false
       drift_dev:analyzer:
         enabled: true
         options: &drift_options
           store_date_time_values_as_text: true
           named_parameters: true
           write_from_json_string_constructor: false
           data_class_to_companions: false
           # Required for make-migrations
           databases:
             main: lib/data/db/database.dart
         generate_for: &drift_generate_for
           - lib/data/db/table/*.dart
           - lib/data/db/table/*.drift
           - lib/data/db/database.dart
           - lib/data/db/logger.dart
           - lib/data/db/person.dart
           - lib/infrastructure/repositories/*.repository.dart
       drift_dev:modular:
         enabled: true
         options: *drift_options
         generate_for: *drift_generate_for