build:
	flutter pub get
	flutter packages pub run build_runner build --delete-conflicting-outputs

watch:
	flutter packages pub run build_runner watch --delete-conflicting-outputs

create_app_icon:
	flutter pub run flutter_launcher_icons

build_release_android:
	flutter build appbundle --flavor prod
