build:
	flutter packages pub run build_runner build

watch:
	flutter packages pub run build_runner watch --delete-conflicting-outputs

create_app_icon:
	flutter pub run flutter_launcher_icons

build_release_android:
	flutter build appbundle --flavor prod
