-- NOTE: This file is auto generated by ./sql-generator

-- AccessRepository.activity.checkOwnerAccess
select
  "activity"."id"
from
  "activity"
where
  "activity"."id" in ($1)
  and "activity"."userId" = $2

-- AccessRepository.activity.checkAlbumOwnerAccess
select
  "activity"."id"
from
  "activity"
  left join "albums" on "activity"."albumId" = "albums"."id"
  and "albums"."deletedAt" is null
where
  "activity"."id" in ($1)
  and "albums"."ownerId" = "activity"."userId"

-- AccessRepository.activity.checkCreateAccess
select
  "albums"."id"
from
  "albums"
  left join "albums_shared_users_users" as "albumUsers" on "albumUsers"."albumsId" = "albums"."id"
  left join "users" on "users"."id" = "albumUsers"."usersId"
  and "users"."deletedAt" is null
where
  "albums"."id" in ($1)
  and "albums"."isActivityEnabled" = $2
  and (
    "albums"."ownerId" = $3
    or "users"."id" = $4
  )
  and "albums"."deletedAt" is null

-- AccessRepository.album.checkOwnerAccess
select
  "albums"."id"
from
  "albums"
where
  "albums"."id" in ($1)
  and "albums"."ownerId" = $2
  and "albums"."deletedAt" is null

-- AccessRepository.album.checkSharedAlbumAccess
select
  "albums"."id"
from
  "albums"
  left join "albums_shared_users_users" as "albumUsers" on "albumUsers"."albumsId" = "albums"."id"
  left join "users" on "users"."id" = "albumUsers"."usersId"
  and "users"."deletedAt" is null
where
  "albums"."id" in ($1)
  and "albums"."deletedAt" is null
  and "users"."id" = $2
  and "albumUsers"."role" in ($3, $4)

-- AccessRepository.album.checkSharedLinkAccess
select
  "shared_links"."albumId"
from
  "shared_links"
where
  "shared_links"."id" = $1
  and "shared_links"."albumId" in ($2)

-- AccessRepository.asset.checkAlbumAccess
select
  "assets"."id",
  "assets"."livePhotoVideoId"
from
  "albums"
  inner join "albums_assets_assets" as "albumAssets" on "albums"."id" = "albumAssets"."albumsId"
  inner join "assets" on "assets"."id" = "albumAssets"."assetsId"
  and "assets"."deletedAt" is null
  left join "albums_shared_users_users" as "albumUsers" on "albumUsers"."albumsId" = "albums"."id"
  left join "users" on "users"."id" = "albumUsers"."usersId"
  and "users"."deletedAt" is null
where
  array["assets"."id", "assets"."livePhotoVideoId"] && array[$1]::uuid []
  and (
    "albums"."ownerId" = $2
    or "users"."id" = $3
  )
  and "albums"."deletedAt" is null

-- AccessRepository.asset.checkOwnerAccess
select
  "assets"."id"
from
  "assets"
where
  "assets"."id" in ($1)
  and "assets"."ownerId" = $2

-- AccessRepository.asset.checkPartnerAccess
select
  "assets"."id"
from
  "partners" as "partner"
  inner join "users" as "sharedBy" on "sharedBy"."id" = "partner"."sharedById"
  and "sharedBy"."deletedAt" is null
  inner join "assets" on "assets"."id" = "sharedBy"."id"
  and "assets"."deletedAt" is null
where
  "partner"."sharedWithId" = $1
  and "assets"."isArchived" = $2
  and "assets"."id" in ($3)

-- AccessRepository.asset.checkSharedLinkAccess
SELECT
  "assets"."id" AS "assetId",
  "assets"."livePhotoVideoId" AS "assetLivePhotoVideoId",
  "albumAssets"."id" AS "albumAssetId",
  "albumAssets"."livePhotoVideoId" AS "albumAssetLivePhotoVideoId"
FROM
  "shared_links" "sharedLink"
  LEFT JOIN "albums" "album" ON "album"."id" = "sharedLink"."albumId"
  AND ("album"."deletedAt" IS NULL)
  LEFT JOIN "shared_link__asset" "assets_sharedLink" ON "assets_sharedLink"."sharedLinksId" = "sharedLink"."id"
  LEFT JOIN "assets" "assets" ON "assets"."id" = "assets_sharedLink"."assetsId"
  AND ("assets"."deletedAt" IS NULL)
  LEFT JOIN "albums_assets_assets" "album_albumAssets" ON "album_albumAssets"."albumsId" = "album"."id"
  LEFT JOIN "assets" "albumAssets" ON "albumAssets"."id" = "album_albumAssets"."assetsId"
  AND ("albumAssets"."deletedAt" IS NULL)
WHERE
  "sharedLink"."id" = $1
  AND array[
    "assets"."id",
    "assets"."livePhotoVideoId",
    "albumAssets"."id",
    "albumAssets"."livePhotoVideoId"
  ] && array[$2]::uuid []

-- AccessRepository.authDevice.checkOwnerAccess
SELECT
  "SessionEntity"."id" AS "SessionEntity_id"
FROM
  "sessions" "SessionEntity"
WHERE
  (
    ("SessionEntity"."userId" = $1)
    AND ("SessionEntity"."id" IN ($2))
  )

-- AccessRepository.memory.checkOwnerAccess
SELECT
  "MemoryEntity"."id" AS "MemoryEntity_id"
FROM
  "memories" "MemoryEntity"
WHERE
  (
    (
      ("MemoryEntity"."id" IN ($1))
      AND ("MemoryEntity"."ownerId" = $2)
    )
  )
  AND ("MemoryEntity"."deletedAt" IS NULL)

-- AccessRepository.person.checkOwnerAccess
SELECT
  "PersonEntity"."id" AS "PersonEntity_id"
FROM
  "person" "PersonEntity"
WHERE
  (
    ("PersonEntity"."id" IN ($1))
    AND ("PersonEntity"."ownerId" = $2)
  )

-- AccessRepository.person.checkFaceOwnerAccess
SELECT
  "AssetFaceEntity"."id" AS "AssetFaceEntity_id"
FROM
  "asset_faces" "AssetFaceEntity"
  LEFT JOIN "assets" "AssetFaceEntity__AssetFaceEntity_asset" ON "AssetFaceEntity__AssetFaceEntity_asset"."id" = "AssetFaceEntity"."assetId"
  AND (
    "AssetFaceEntity__AssetFaceEntity_asset"."deletedAt" IS NULL
  )
WHERE
  (
    ("AssetFaceEntity"."id" IN ($1))
    AND (
      (
        (
          "AssetFaceEntity__AssetFaceEntity_asset"."ownerId" = $2
        )
      )
    )
  )

-- AccessRepository.partner.checkUpdateAccess
SELECT
  "partner"."sharedById" AS "partner_sharedById",
  "partner"."sharedWithId" AS "partner_sharedWithId"
FROM
  "partners" "partner"
WHERE
  "partner"."sharedById" IN ($1)
  AND "partner"."sharedWithId" = $2

-- AccessRepository.stack.checkOwnerAccess
SELECT
  "StackEntity"."id" AS "StackEntity_id"
FROM
  "asset_stack" "StackEntity"
WHERE
  (
    ("StackEntity"."id" IN ($1))
    AND ("StackEntity"."ownerId" = $2)
  )

-- AccessRepository.tag.checkOwnerAccess
SELECT
  "TagEntity"."id" AS "TagEntity_id"
FROM
  "tags" "TagEntity"
WHERE
  (
    ("TagEntity"."id" IN ($1))
    AND ("TagEntity"."userId" = $2)
  )

-- AccessRepository.timeline.checkPartnerAccess
SELECT
  "partner"."sharedById" AS "partner_sharedById",
  "partner"."sharedWithId" AS "partner_sharedWithId"
FROM
  "partners" "partner"
WHERE
  "partner"."sharedById" IN ($1)
  AND "partner"."sharedWithId" = $2
