-- NOTE: This file is auto generated by ./sql-generator

-- AlbumUserRepository.create
insert into
  "album_user" ("usersId", "albumsId")
values
  ($1, $2)
returning
  "usersId",
  "albumsId",
  "role"

-- AlbumUserRepository.update
update "album_user"
set
  "role" = $1
where
  "usersId" = $2
  and "albumsId" = $3
returning
  *

-- AlbumUserRepository.delete
delete from "album_user"
where
  "usersId" = $1
  and "albumsId" = $2
