-- NOTE: This file is auto generated by ./sql-generator

-- AuthChallengeRepository.consume
delete from "auth_challenge"
where
  "challenge" = $1
  and "type" = $2
  and "expiresAt" > $3
returning
  "id",
  "userId"

-- AuthChallengeRepository.deleteExpired
delete from "auth_challenge"
where
  "expiresAt" <= $1
