-- NOTE: This file is auto generated by ./sql-generator

-- FaceIdentityRepository.resolveScopedPersonTokens
select
  "id",
  "identityId"
from
  "person"
where
  "ownerId" = $1
  and "id" in ($2)
select
  "shared_space_person"."id",
  "shared_space_person"."identityId",
  "shared_space_person"."spaceId",
  "shared_space_member"."showInTimeline"
from
  "shared_space_person"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_person"."spaceId"
  and "shared_space_member"."userId" = $1
where
  "shared_space_person"."id" in ($2)

-- FaceIdentityRepository.searchAccessiblePeople
WITH
  timeline_spaces AS (
    SELECT
      "spaceId"
    FROM
      shared_space_member
    WHERE
      "userId" = $1
      AND "showInTimeline" = true
  ),
  accessible_faces AS (
    SELECT
      face_identity_face."identityId",
      asset_face."assetId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN asset ON asset.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
      AND asset."deletedAt" IS NULL
      AND asset.visibility = $2
      AND (
        asset."ownerId" = $3
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_asset
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_asset."spaceId"
          WHERE
            shared_space_asset."assetId" = asset.id
        )
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_library
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_library."spaceId"
          WHERE
            shared_space_library."libraryId" = asset."libraryId"
        )
      )
  ),
  accessible_profiles AS (
    SELECT
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      person.id AS "profileId",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $4
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      shared_space_person.id AS "profileId",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_person."spaceId"
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $5
    WHERE
      shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = shared_space_person."identityId"
      )
  ),
  eligible_profiles AS (
    SELECT
      *
    FROM
      accessible_profiles
    WHERE
      (
        $6::boolean
        OR "isHidden" = false
      )
      AND (
        $7 = ''
        OR name ILIKE $8
      )
  ),
  identity_counts AS (
    SELECT
      accessible_faces."identityId",
      COUNT(DISTINCT accessible_faces."assetId") AS "visibleAssetCount"
    FROM
      accessible_faces
    WHERE
      EXISTS (
        SELECT
          1
        FROM
          eligible_profiles
        WHERE
          eligible_profiles."identityId" = accessible_faces."identityId"
      )
    GROUP BY
      accessible_faces."identityId"
  ),
  best_profiles AS (
    SELECT DISTINCT
      ON ("identityId") "identityId",
      name
    FROM
      eligible_profiles
    ORDER BY
      "identityId",
      NULLIF(name, '') IS NULL,
      "profileRank",
      lower(name),
      "updatedAt" DESC,
      "profileId"
  )
SELECT
  identity_counts."identityId",
  identity_counts."visibleAssetCount"
FROM
  identity_counts
  INNER JOIN best_profiles ON best_profiles."identityId" = identity_counts."identityId"
WHERE
  NULLIF(best_profiles.name, '') IS NOT NULL
  OR identity_counts."visibleAssetCount" >= $9
ORDER BY
  NULLIF(best_profiles.name, '') IS NULL,
  lower(best_profiles.name),
  identity_counts."visibleAssetCount" DESC,
  identity_counts."identityId"
LIMIT
  $10
OFFSET
  $11

-- FaceIdentityRepository.getAccessiblePersonFilterSuggestions
WITH
  timeline_spaces AS (
    SELECT
      "spaceId"
    FROM
      shared_space_member
    WHERE
      "userId" = $1
      AND "showInTimeline" = true
  ),
  accessible_faces AS (
    SELECT
      face_identity_face."identityId",
      asset_face."assetId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN asset ON asset.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
      AND asset."deletedAt" IS NULL
      AND asset.visibility = $2
      AND (
        asset."ownerId" = $3
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_asset
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_asset."spaceId"
          WHERE
            shared_space_asset."assetId" = asset.id
        )
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_library
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_library."spaceId"
          WHERE
            shared_space_library."libraryId" = asset."libraryId"
        )
      )
  ),
  accessible_profiles AS (
    SELECT
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      person.id AS "profileId",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $4
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      shared_space_person.id AS "profileId",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_person."spaceId"
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $5
    WHERE
      shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = shared_space_person."identityId"
      )
  ),
  eligible_profiles AS (
    SELECT
      *
    FROM
      accessible_profiles
    WHERE
      (
        $6::boolean
        OR "isHidden" = false
      )
      AND (
        $7 = ''
        OR name ILIKE $8
      )
  ),
  identity_counts AS (
    SELECT
      accessible_faces."identityId",
      COUNT(DISTINCT accessible_faces."assetId") AS "visibleAssetCount"
    FROM
      accessible_faces
    WHERE
      EXISTS (
        SELECT
          1
        FROM
          eligible_profiles
        WHERE
          eligible_profiles."identityId" = accessible_faces."identityId"
      )
    GROUP BY
      accessible_faces."identityId"
  ),
  best_profiles AS (
    SELECT DISTINCT
      ON ("identityId") "identityId",
      name
    FROM
      eligible_profiles
    ORDER BY
      "identityId",
      NULLIF(name, '') IS NULL,
      "profileRank",
      lower(name),
      "updatedAt" DESC,
      "profileId"
  )
SELECT
  identity_counts."identityId",
  identity_counts."visibleAssetCount"
FROM
  identity_counts
  INNER JOIN best_profiles ON best_profiles."identityId" = identity_counts."identityId"
WHERE
  NULLIF(best_profiles.name, '') IS NOT NULL
  OR identity_counts."visibleAssetCount" >= $9
ORDER BY
  NULLIF(best_profiles.name, '') IS NULL,
  lower(best_profiles.name),
  identity_counts."visibleAssetCount" DESC,
  identity_counts."identityId"
LIMIT
  $10
OFFSET
  $11

-- FaceIdentityRepository.getAccessiblePeopleIdentityPage
WITH
  timeline_spaces AS (
    SELECT
      "spaceId"
    FROM
      shared_space_member
    WHERE
      "userId" = $1
      AND "showInTimeline" = true
  ),
  accessible_faces AS (
    SELECT
      face_identity_face."identityId",
      asset_face."assetId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN asset ON asset.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
      AND asset."deletedAt" IS NULL
      AND asset.visibility = $2
      AND (
        asset."ownerId" = $3
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_asset
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_asset."spaceId"
          WHERE
            shared_space_asset."assetId" = asset.id
        )
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_library
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_library."spaceId"
          WHERE
            shared_space_library."libraryId" = asset."libraryId"
        )
      )
  ),
  accessible_profiles AS (
    SELECT
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      person.id AS "profileId",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $4
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      shared_space_person.id AS "profileId",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_person."spaceId"
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $5
    WHERE
      shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = shared_space_person."identityId"
      )
  ),
  eligible_profiles AS (
    SELECT
      *
    FROM
      accessible_profiles
    WHERE
      (
        $6::boolean
        OR "isHidden" = false
      )
      AND (
        $7 = ''
        OR name ILIKE $8
      )
  ),
  identity_counts AS (
    SELECT
      accessible_faces."identityId",
      COUNT(DISTINCT accessible_faces."assetId") AS "visibleAssetCount"
    FROM
      accessible_faces
    WHERE
      EXISTS (
        SELECT
          1
        FROM
          eligible_profiles
        WHERE
          eligible_profiles."identityId" = accessible_faces."identityId"
      )
    GROUP BY
      accessible_faces."identityId"
  ),
  best_profiles AS (
    SELECT DISTINCT
      ON ("identityId") "identityId",
      name
    FROM
      eligible_profiles
    ORDER BY
      "identityId",
      NULLIF(name, '') IS NULL,
      "profileRank",
      lower(name),
      "updatedAt" DESC,
      "profileId"
  )
SELECT
  identity_counts."identityId",
  identity_counts."visibleAssetCount"
FROM
  identity_counts
  INNER JOIN best_profiles ON best_profiles."identityId" = identity_counts."identityId"
WHERE
  NULLIF(best_profiles.name, '') IS NOT NULL
  OR identity_counts."visibleAssetCount" >= $9
ORDER BY
  NULLIF(best_profiles.name, '') IS NULL,
  lower(best_profiles.name),
  identity_counts."visibleAssetCount" DESC,
  identity_counts."identityId"
LIMIT
  $10
OFFSET
  $11

-- FaceIdentityRepository.hydrateAccessiblePeople
WITH
  requested_identities AS (
    SELECT
      *
    FROM
      unnest(array[$1]::uuid[]) WITH ORDINALITY AS requested ("identityId", ord)
  ),
  timeline_spaces AS (
    SELECT
      "spaceId"
    FROM
      shared_space_member
    WHERE
      "userId" = $2
      AND "showInTimeline" = true
  ),
  accessible_faces AS (
    SELECT
      face_identity_face."identityId",
      asset_face."assetId"
    FROM
      face_identity_face
      INNER JOIN requested_identities ON requested_identities."identityId" = face_identity_face."identityId"
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN asset ON asset.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
      AND asset."deletedAt" IS NULL
      AND asset.visibility = $3
      AND (
        asset."ownerId" = $4
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_asset
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_asset."spaceId"
          WHERE
            shared_space_asset."assetId" = asset.id
        )
        OR EXISTS (
          SELECT
            1
          FROM
            shared_space_library
            INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_library."spaceId"
          WHERE
            shared_space_library."libraryId" = asset."libraryId"
        )
      )
  ),
  asset_counts AS (
    SELECT
      "identityId",
      COUNT(DISTINCT "assetId") AS "numberOfAssets"
    FROM
      accessible_faces
    GROUP BY
      "identityId"
  ),
  profiles AS (
    SELECT
      'user-person'::text AS "profileType",
      person.id AS "profileId",
      NULL::uuid AS "spaceId",
      person."identityId",
      person.name,
      person."birthDate",
      person."thumbnailPath",
      person."isHidden",
      person."isFavorite",
      person.color,
      person."updatedAt",
      person.type,
      person.species,
      0 AS "profileRank"
    FROM
      person
      INNER JOIN requested_identities ON requested_identities."identityId" = person."identityId"
    WHERE
      person."ownerId" = $5
      AND (
        $6::boolean
        OR person."isHidden" = false
      )
    UNION ALL
    SELECT
      'space-person'::text AS "profileType",
      shared_space_person.id AS "profileId",
      shared_space_person."spaceId",
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."birthDate",
      ''::text AS "thumbnailPath",
      shared_space_person."isHidden",
      NULL::boolean AS "isFavorite",
      NULL::text AS color,
      shared_space_person."updatedAt",
      shared_space_person.type,
      NULL::text AS species,
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      INNER JOIN requested_identities ON requested_identities."identityId" = shared_space_person."identityId"
      INNER JOIN timeline_spaces ON timeline_spaces."spaceId" = shared_space_person."spaceId"
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $7
    WHERE
      $8::boolean
      OR shared_space_person."isHidden" = false
  ),
  ranked_profiles AS (
    SELECT
      profiles.*,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          NULLIF(profiles.name, '') IS NULL,
          profiles."profileRank",
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS rn
    FROM
      profiles
    WHERE
      EXISTS (
        SELECT
          1
        FROM
          accessible_faces
        WHERE
          accessible_faces."identityId" = profiles."identityId"
      )
  )
SELECT
  ranked_profiles."profileType",
  ranked_profiles."profileId",
  ranked_profiles."spaceId",
  ranked_profiles.name,
  ranked_profiles."birthDate",
  ranked_profiles."thumbnailPath",
  ranked_profiles."isHidden",
  ranked_profiles."isFavorite",
  ranked_profiles.color,
  ranked_profiles."updatedAt",
  ranked_profiles.type,
  ranked_profiles.species,
  asset_counts."numberOfAssets"
FROM
  requested_identities
  INNER JOIN ranked_profiles ON ranked_profiles."identityId" = requested_identities."identityId"
  AND ranked_profiles.rn = 1
  LEFT JOIN asset_counts ON asset_counts."identityId" = requested_identities."identityId"
ORDER BY
  requested_identities.ord

-- FaceIdentityRepository.ensurePersonIdentity
begin
select
  "id",
  "identityId",
  "type",
  "faceAssetId"
from
  "person"
where
  "id" = $1
rollback

-- FaceIdentityRepository.ensureSpacePersonIdentity
begin
select
  "id",
  "identityId",
  "type",
  "representativeFaceId"
from
  "shared_space_person"
where
  "id" = $1
rollback

-- FaceIdentityRepository.linkFace
insert into
  "face_identity_face" (
    "assetFaceId",
    "identityId",
    "source",
    "confidence"
  )
values
  ($1, $2, $3, $4)
on conflict ("assetFaceId") do update
set
  "identityId" = $5,
  "source" = $6,
  "confidence" = $7
returning
  *

-- FaceIdentityRepository.replaceFaceIdentity
insert into
  "face_identity_face" (
    "assetFaceId",
    "identityId",
    "source",
    "confidence"
  )
values
  ($1, $2, $3, $4)
on conflict ("assetFaceId") do update
set
  "identityId" = $5,
  "source" = $6,
  "confidence" = $7
returning
  *

-- FaceIdentityRepository.updateRepresentativeFace
update "face_identity"
set
  "representativeFaceId" = $1
where
  "id" = $2
insert into
  "face_identity_face" (
    "assetFaceId",
    "identityId",
    "source",
    "confidence"
  )
values
  ($1, $2, $3, $4)
on conflict ("assetFaceId") do update
set
  "identityId" = $5,
  "source" = $6,
  "confidence" = $7
returning
  *

-- FaceIdentityRepository.unlinkFaces
delete from "face_identity_face"
where
  "assetFaceId" in ($1)

-- FaceIdentityRepository.unlinkFacesBySourceType
delete from "face_identity_face"
where
  "assetFaceId" in (
    select
      "id"
    from
      "asset_face"
    where
      "sourceType" = $1
  )
