-- NOTE: This file is auto generated by ./sql-generator

-- MemoryRepository.statistics
select
  count(*) as "total"
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $1
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $2
              and coalesce(
                (
                  asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                )::boolean,
                false
              ) = true
          )
        )
    )
  )

-- MemoryRepository.statistics (date filter)
select
  count(*) as "total"
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $1
  )
  and (
    "hideAt" is null
    or "hideAt" >= $2
  )
  and "deletedAt" is null
  and "ownerId" = $3
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $4
              and coalesce(
                (
                  asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                )::boolean,
                false
              ) = true
          )
        )
    )
  )

-- MemoryRepository.search
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                ) = true
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $2
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $3
              and coalesce(
                (
                  asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                )::boolean,
                false
              ) = true
          )
        )
    )
  )
order by
  "memoryAt" desc

-- MemoryRepository.search (date filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                ) = true
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $2
  )
  and (
    "hideAt" is null
    or "hideAt" >= $3
  )
  and "deletedAt" is null
  and "ownerId" = $4
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $5
              and coalesce(
                (
                  asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                )::boolean,
                false
              ) = true
          )
        )
    )
  )
order by
  "memoryAt" desc

-- MemoryRepository.get
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                ) = true
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $2
  and "deletedAt" is null
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $3
              and coalesce(
                (
                  asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                )::boolean,
                (
                  asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                )::boolean,
                false
              ) = true
          )
        )
    )
  )

-- MemoryRepository.update
update "memory"
set
  "ownerId" = $1,
  "isSaved" = $2
where
  "id" = $3

-- MemoryRepository.delete
delete from "memory"
where
  "id" = $1

-- MemoryRepository.getAssetIds
select
  "assetId"
from
  "memory_asset"
where
  "memoriesId" = $1
  and "assetId" in ($2)

-- MemoryRepository.addAssetIds
insert into
  "memory_asset" ("memoriesId", "assetId")
values
  ($1, $2)
