-- NOTE: This file is auto generated by ./sql-generator

-- PasskeyRepository.delete
delete from "passkey"
where
  "id" = $1::uuid

-- PasskeyRepository.getByCredentialId
select
  *
from
  "passkey"
where
  "credentialId" = $1

-- PasskeyRepository.get
select
  "id",
  "name",
  "userId",
  "credentialId",
  "transports",
  "createdAt",
  "updatedAt",
  "usedAt"
from
  "passkey"
where
  "id" = $1::uuid

-- PasskeyRepository.search
select
  "id",
  "name",
  "userId",
  "credentialId",
  "transports",
  "createdAt",
  "updatedAt",
  "usedAt"
from
  "passkey"
where
  "userId" = $1
order by
  "createdAt" desc
