-- NOTE: This file is auto generated by ./sql-generator

-- SearchRepository.getEmbedding
select
  "embedding"
from
  "smart_search"
where
  "assetId" = $1

-- SearchRepository.searchMetadata
select
  "asset".*
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."fileCreatedAt" >= $2
  and "asset_exif"."lensModel" = $3
  and "asset"."ownerId" = any ($4::uuid[])
  and "asset"."isFavorite" = $5
  and "asset"."deletedAt" is null
order by
  "asset"."fileCreatedAt" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadata (identity-filter)
select
  "asset".*
from
  "asset"
  inner join (
    select
      "asset_face"."assetId"
    from
      "asset_face"
      inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
    where
      "face_identity_face"."identityId" = any ($1::uuid[])
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
    group by
      "asset_face"."assetId"
    having
      count(distinct "face_identity_face"."identityId") = $2
  ) as "has_face_identities" on "has_face_identities"."assetId" = "asset"."id"
where
  "asset"."visibility" = $3
  and (
    "asset"."ownerId" = any ($4::uuid[])
    or exists (
      select
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_asset"."spaceId" = any ($5::uuid[])
    )
    or exists (
      select
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = any ($6::uuid[])
    )
  )
  and "asset"."deletedAt" is null
order by
  "asset"."fileCreatedAt" desc
limit
  $7
offset
  $8

-- SearchRepository.searchStatistics
select
  count(*) as "total"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."fileCreatedAt" >= $2
  and "asset_exif"."lensModel" = $3
  and "asset"."ownerId" = any ($4::uuid[])
  and "asset"."isFavorite" = $5
  and "asset"."deletedAt" is null

-- SearchRepository.searchRandom
select
  "asset".*
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."fileCreatedAt" >= $2
  and "asset_exif"."lensModel" = $3
  and "asset"."ownerId" = any ($4::uuid[])
  and "asset"."isFavorite" = $5
  and "asset"."deletedAt" is null
order by
  random()
limit
  $6

-- SearchRepository.searchLargeAssets
select
  "asset".*,
  to_json("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."fileCreatedAt" >= $2
  and "asset_exif"."lensModel" = $3
  and "asset"."ownerId" = any ($4::uuid[])
  and "asset"."isFavorite" = $5
  and "asset"."deletedAt" is null
  and "asset_exif"."fileSizeInByte" > $6
order by
  "asset_exif"."fileSizeInByte" desc
limit
  $7

-- SearchRepository.searchSmart
begin
set
  local vchordrq.probes = 1
select
  *
from
  (
    select
      "asset".*
    from
      "asset"
      inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
      inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
    where
      "asset"."visibility" = $1
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and exists (
        select
        from
          "shared_space_person_face"
          inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "shared_space_person_face"."personId" = any ($5::uuid[])
      )
      and "asset"."fileCreatedAt" >= $6
      and "asset_exif"."lensModel" = $7
      and "asset"."isFavorite" = $8
      and "asset"."deletedAt" is null
      and (smart_search.embedding <=> $9) <= $10
    order by
      smart_search.embedding <=> $11
    limit
      $12
  ) as "candidates"
order by
  "candidates"."fileCreatedAt" desc nulls last,
  "candidates"."id"
limit
  $13
offset
  $14
commit

-- SearchRepository.getSmartSearchFacets
begin
set
  local vchordrq.probes = 1
drop table if exists smart_search_facet_candidates
create temporary table smart_search_facet_candidates on
commit
drop as (
  select
    "asset"."id"
  from
    "asset"
    inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
  where
    "asset"."visibility" = $1
    and (
      "asset"."ownerId" = any ($2::uuid[])
      or exists (
        select
        from
          "shared_space_asset"
        where
          "shared_space_asset"."assetId" = "asset"."id"
          and "shared_space_asset"."spaceId" = any ($3::uuid[])
      )
      or exists (
        select
        from
          "shared_space_library"
        where
          "shared_space_library"."libraryId" = "asset"."libraryId"
          and "shared_space_library"."spaceId" = any ($4::uuid[])
      )
    )
    and "asset"."deletedAt" is null
    and (smart_search.embedding <=> $5) <= $6
    and "smart_search"."embedding" is not null
)
create index smart_search_facet_candidates_asset_id_idx on smart_search_facet_candidates ("id")
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."country" = $6
      and "asset_exif"."make" = $7
      and "asset_exif"."rating" >= $8
  ) as "filtered"
with
  "asset" as (
    select
      date_trunc('MONTH', "localDateTime" AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' as "timeBucket"
    from
      "asset"
    where
      "asset"."id" in (
        select
          "asset"."id"
        from
          "asset"
          inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
          inner join (
            select
              "assetId"
            from
              "tag_asset"
              inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
            where
              "tag_closure"."id_ancestor" = any ($1::uuid[])
            group by
              "assetId"
            having
              count(distinct "tag_closure"."id_ancestor") >= $2
          ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
        where
          "asset"."id" in (
            select
              "candidates"."id"
            from
              smart_search_facet_candidates as "candidates"
          )
          and "asset"."type" = $3
          and "asset_exif"."country" = $4
          and "asset_exif"."make" = $5
          and "asset_exif"."rating" >= $6
      )
  )
select
  ("timeBucket" AT TIME ZONE 'UTC')::date::text as "timeBucket",
  count(*) as "count"
from
  "asset"
group by
  "timeBucket"
order by
  "timeBucket" desc
select distinct
  "country"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."make" = $6
      and "asset_exif"."rating" >= $7
  )
  and "country" is not null
  and "country" != $8
order by
  "country"
select distinct
  "city"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."country" = $6
      and "asset_exif"."make" = $7
      and "asset_exif"."rating" >= $8
  )
  and "city" is not null
  and "city" != $9
order by
  "city"
select distinct
  "make"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."country" = $6
      and "asset_exif"."rating" >= $7
  )
  and "make" is not null
  and "make" != $8
order by
  "make"
select distinct
  "model"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."country" = $6
      and "asset_exif"."make" = $7
      and "asset_exif"."rating" >= $8
  )
  and "model" is not null
  and "model" != $9
order by
  "model"
select distinct
  "tag"."id",
  "tag"."value"
from
  "tag"
  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
where
  "tag_asset"."assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $1
      and "asset"."fileCreatedAt" <= $2
      and "asset"."type" = $3
      and "asset_exif"."country" = $4
      and "asset_exif"."make" = $5
      and "asset_exif"."rating" >= $6
  )
order by
  "tag"."value"
WITH
  filtered_assets AS (
    (
      select
        "asset"."id"
      from
        "asset"
        inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
        inner join (
          select
            "assetId"
          from
            "tag_asset"
            inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
          where
            "tag_closure"."id_ancestor" = any ($1::uuid[])
          group by
            "assetId"
          having
            count(distinct "tag_closure"."id_ancestor") >= $2
        ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
      where
        "asset"."id" in (
          select
            "candidates"."id"
          from
            smart_search_facet_candidates as "candidates"
        )
        and "asset"."fileCreatedAt" >= $3
        and "asset"."fileCreatedAt" <= $4
        and "asset"."type" = $5
        and "asset_exif"."country" = $6
        and "asset_exif"."make" = $7
        and "asset_exif"."rating" >= $8
    )
  ),
  identity_faces AS (
    SELECT DISTINCT
      face_identity_face."identityId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN filtered_assets ON filtered_assets.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
  ),
  profiles AS (
    SELECT
      'user-person'::text AS "profileType",
      person.id AS "profileId",
      NULL::uuid AS "spaceId",
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $9
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      'space-person'::text AS "profileType",
      shared_space_person.id AS "profileId",
      shared_space_person."spaceId",
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $10
    WHERE
      shared_space_person."spaceId" = any ($11::uuid[])
      AND shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          shared_space_person_face
          INNER JOIN asset_face AS profile_face ON profile_face.id = shared_space_person_face."assetFaceId"
        WHERE
          shared_space_person_face."personId" = shared_space_person.id
          AND profile_face."deletedAt" IS NULL
          AND profile_face."isVisible" = true
      )
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = shared_space_person."identityId"
      )
  ),
  ranked_profiles AS (
    SELECT
      profiles.*,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          NULLIF(profiles.name, '') IS NULL,
          profiles."profileRank",
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS display_rn,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          CASE
            WHEN profiles."profileType" = 'user-person' THEN 0
            ELSE profiles."profileRank"
          END,
          NULLIF(profiles.name, '') IS NULL,
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS primary_rn
    FROM
      profiles
    WHERE
      profiles."isHidden" = false
  )
SELECT
  CASE
    WHEN primary_profiles."profileType" = 'space-person' THEN 'space-person:' || primary_profiles."profileId"::text
    ELSE 'person:' || primary_profiles."profileId"::text
  END AS id,
  COALESCE(
    NULLIF(display_profiles.name, ''),
    primary_profiles.name,
    ''
  ) AS name,
  primary_profiles."profileType",
  primary_profiles."profileId",
  primary_profiles."spaceId"
FROM
  ranked_profiles AS primary_profiles
  INNER JOIN ranked_profiles AS display_profiles ON display_profiles."identityId" = primary_profiles."identityId"
  AND display_profiles.display_rn = 1
WHERE
  primary_profiles.primary_rn = 1
ORDER BY
  NULLIF(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    ),
    ''
  ) IS NULL,
  lower(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    )
  ),
  primary_profiles."profileId"
select distinct
  "rating"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset"."type" = $5
      and "asset_exif"."country" = $6
      and "asset_exif"."make" = $7
  )
  and "rating" is not null
  and "rating" > $8
order by
  "rating"
select distinct
  "type"
from
  "asset"
where
  "id" in (
    select
      "asset"."id"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "assetId"
        from
          "tag_asset"
          inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
        where
          "tag_closure"."id_ancestor" = any ($1::uuid[])
        group by
          "assetId"
        having
          count(distinct "tag_closure"."id_ancestor") >= $2
      ) as "has_tags" on "has_tags"."assetId" = "asset"."id"
    where
      "asset"."id" in (
        select
          "candidates"."id"
        from
          smart_search_facet_candidates as "candidates"
      )
      and "asset"."fileCreatedAt" >= $3
      and "asset"."fileCreatedAt" <= $4
      and "asset_exif"."country" = $5
      and "asset_exif"."make" = $6
      and "asset_exif"."rating" >= $7
  )
order by
  "type"
commit

-- SearchRepository.searchFaces
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "asset_face"."id",
      "asset_face"."personId",
      face_search.embedding <=> $1 as "distance"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
      left join "person" on "person"."id" = "asset_face"."personId"
    where
      "asset"."ownerId" = any ($2::uuid[])
      and "asset"."deletedAt" is null
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
commit

-- SearchRepository.searchPlaces
select
  *
from
  "geodata_places"
where
  f_unaccent (name) %>> f_unaccent ($1)
  or f_unaccent ("admin2Name") %>> f_unaccent ($2)
  or f_unaccent ("admin1Name") %>> f_unaccent ($3)
  or f_unaccent ("alternateNames") %>> f_unaccent ($4)
order by
  coalesce(f_unaccent (name) <->>> f_unaccent ($5), 0.1) + coalesce(
    f_unaccent ("admin2Name") <->>> f_unaccent ($6),
    0.1
  ) + coalesce(
    f_unaccent ("admin1Name") <->>> f_unaccent ($7),
    0.1
  ) + coalesce(
    f_unaccent ("alternateNames") <->>> f_unaccent ($8),
    0.1
  )
limit
  $9

-- SearchRepository.getAssetsByCity
with recursive
  "cte" as (
    (
      select
        "city",
        "assetId"
      from
        "asset_exif"
        inner join "asset" on "asset"."id" = "asset_exif"."assetId"
      where
        "asset"."ownerId" = any ($1::uuid[])
        and "asset"."visibility" = $2
        and "asset"."type" = $3
        and "asset"."deletedAt" is null
      order by
        "city"
      limit
        $4
    )
    union all
    (
      select
        "l"."city",
        "l"."assetId"
      from
        "cte"
        inner join lateral (
          select
            "city",
            "assetId"
          from
            "asset_exif"
            inner join "asset" on "asset"."id" = "asset_exif"."assetId"
          where
            "asset"."ownerId" = any ($5::uuid[])
            and "asset"."visibility" = $6
            and "asset"."type" = $7
            and "asset"."deletedAt" is null
            and "asset_exif"."city" > "cte"."city"
          order by
            "city"
          limit
            $8
        ) as "l" on true
    )
  )
select
  "asset".*,
  to_jsonb("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "cte" on "asset"."id" = "cte"."assetId"
order by
  "asset_exif"."city"

-- SearchRepository.getStates
select distinct
  on ("state") "state"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "visibility" = $1
  and "deletedAt" is null
  and "state" is not null
  and "state" != $2
  and "asset"."ownerId" = any ($3::uuid[])

-- SearchRepository.getCities
select distinct
  "city"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and "asset"."ownerId" = any ($2::uuid[])
  )
  and "city" is not null
  and "city" != $3
order by
  "city"

-- SearchRepository.getCameraMakes
select distinct
  on ("make") "make"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "visibility" = $1
  and "deletedAt" is null
  and "make" is not null
  and "make" != $2
  and "asset"."ownerId" = any ($3::uuid[])

-- SearchRepository.getCameraModels
select distinct
  on ("model") "model"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "visibility" = $1
  and "deletedAt" is null
  and "model" is not null
  and "model" != $2
  and "asset"."ownerId" = any ($3::uuid[])

-- SearchRepository.getCameraLensModels
select distinct
  on ("lensModel") "lensModel"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "visibility" = $1
  and "deletedAt" is null
  and "lensModel" is not null
  and "lensModel" != $2
  and "asset"."ownerId" = any ($3::uuid[])

-- SearchRepository.getAccessibleTags
select distinct
  "tag"."id",
  "tag"."value"
from
  "tag"
  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
  inner join "asset" on "tag_asset"."assetId" = "asset"."id"
where
  "asset"."visibility" = $1
  and "asset"."deletedAt" is null
  and "asset"."ownerId" = any ($2::uuid[])
order by
  "tag"."value"

-- SearchRepository.getFilterSuggestions (identity-filter-suggestions)
select distinct
  "country"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "country" is not null
  and "country" != $7
order by
  "country"
select distinct
  "make"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "make" is not null
  and "make" != $7
order by
  "make"
select distinct
  "tag"."id",
  "tag"."value"
from
  "tag"
  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
where
  "tag_asset"."assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
order by
  "tag"."value"
WITH
  filtered_assets AS (
    (
      select
        "asset"."id"
      from
        "asset"
      where
        "asset"."visibility" = $1
        and "asset"."deletedAt" is null
        and (
          "asset"."ownerId" = any ($2::uuid[])
          or exists (
            select
            from
              "shared_space_asset"
            where
              "shared_space_asset"."assetId" = "asset"."id"
              and "shared_space_asset"."spaceId" = any ($3::uuid[])
          )
          or exists (
            select
            from
              "shared_space_library"
            where
              "shared_space_library"."libraryId" = "asset"."libraryId"
              and "shared_space_library"."spaceId" = any ($4::uuid[])
          )
        )
        and "asset"."fileCreatedAt" >= $5
    )
  ),
  identity_faces AS (
    SELECT DISTINCT
      face_identity_face."identityId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN filtered_assets ON filtered_assets.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
  ),
  profiles AS (
    SELECT
      'user-person'::text AS "profileType",
      person.id AS "profileId",
      NULL::uuid AS "spaceId",
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $6
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      'space-person'::text AS "profileType",
      shared_space_person.id AS "profileId",
      shared_space_person."spaceId",
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $7
    WHERE
      shared_space_person."spaceId" = any ($8::uuid[])
      AND shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          shared_space_person_face
          INNER JOIN asset_face AS profile_face ON profile_face.id = shared_space_person_face."assetFaceId"
        WHERE
          shared_space_person_face."personId" = shared_space_person.id
          AND profile_face."deletedAt" IS NULL
          AND profile_face."isVisible" = true
      )
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = shared_space_person."identityId"
      )
  ),
  ranked_profiles AS (
    SELECT
      profiles.*,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          NULLIF(profiles.name, '') IS NULL,
          profiles."profileRank",
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS display_rn,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          CASE
            WHEN profiles."profileType" = 'user-person' THEN 0
            ELSE profiles."profileRank"
          END,
          NULLIF(profiles.name, '') IS NULL,
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS primary_rn
    FROM
      profiles
    WHERE
      profiles."isHidden" = false
  )
SELECT
  CASE
    WHEN primary_profiles."profileType" = 'space-person' THEN 'space-person:' || primary_profiles."profileId"::text
    ELSE 'person:' || primary_profiles."profileId"::text
  END AS id,
  COALESCE(
    NULLIF(display_profiles.name, ''),
    primary_profiles.name,
    ''
  ) AS name,
  primary_profiles."profileType",
  primary_profiles."profileId",
  primary_profiles."spaceId"
FROM
  ranked_profiles AS primary_profiles
  INNER JOIN ranked_profiles AS display_profiles ON display_profiles."identityId" = primary_profiles."identityId"
  AND display_profiles.display_rn = 1
WHERE
  primary_profiles.primary_rn = 1
ORDER BY
  NULLIF(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    ),
    ''
  ) IS NULL,
  lower(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    )
  ),
  primary_profiles."profileId"
select distinct
  "rating"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "rating" is not null
  and "rating" > $7
order by
  "rating"
select distinct
  "type"
from
  "asset"
where
  "id" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
order by
  "type"
