-- NOTE: This file is auto generated by ./sql-generator

-- SharedLinkAssetRepository.copySharedLinks
insert into
  "shared_link_asset"
select
  $1 as "assetsId",
  "shared_link_asset"."sharedLinksId"
from
  "shared_link_asset"
where
  "shared_link_asset"."assetsId" = $2
on conflict do nothing
