-- NOTE: This file is auto generated by ./sql-generator

-- SharedSpaceRepository.getById
select
  *
from
  "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getAllByUserId
select
  "shared_space".*
from
  "shared_space"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space"."id"
where
  "shared_space_member"."userId" = $1

-- SharedSpaceRepository.update
update "shared_space"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.remove
delete from "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getMembers
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1

-- SharedSpaceRepository.getMember
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1
  and "shared_space_member"."userId" = $2

-- SharedSpaceRepository.updateMember
update "shared_space_member"
set
  "role" = $1
where
  "spaceId" = $2
  and "userId" = $3
returning
  *

-- SharedSpaceRepository.removeMember
delete from "shared_space_member"
where
  "spaceId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getSpaceIdsForTimeline
select
  "spaceId"
from
  "shared_space_member"
where
  "userId" = $1
  and "showInTimeline" = $2

-- SharedSpaceRepository.getSpaceIdsWithFaceRecognitionEnabled
select
  "id"
from
  "shared_space"
where
  "faceRecognitionEnabled" = $1

-- SharedSpaceRepository.getAssetCount
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $3
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $4
  ) as "combined"

-- SharedSpaceRepository.getEditableByAssetIds
select distinct
  "shared_space_asset"."spaceId"
from
  "shared_space_asset"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
where
  "shared_space_asset"."assetId" in ($1)
  and "shared_space_member"."userId" = $2
  and "shared_space_member"."role" in ($3, $4)

-- SharedSpaceRepository.removeAssets
delete from "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" in ($2)

-- SharedSpaceRepository.removeLibrary
delete from "shared_space_library"
where
  "spaceId" = $1
  and "libraryId" = $2

-- SharedSpaceRepository.getLinkedLibraries
select
  *
from
  "shared_space_library"
where
  "spaceId" = $1

-- SharedSpaceRepository.getSpacesLinkedToLibrary
select
  "shared_space_library".*,
  "shared_space"."faceRecognitionEnabled"
from
  "shared_space_library"
  inner join "shared_space" on "shared_space"."id" = "shared_space_library"."spaceId"
where
  "shared_space_library"."libraryId" = $1

-- SharedSpaceRepository.hasLibraryLink
select
  "spaceId"
from
  "shared_space_library"
where
  "spaceId" = $1
  and "libraryId" = $2

-- SharedSpaceRepository.getRecentAssets
select
  "combined"."id",
  "combined"."thumbhash"
from
  (
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."type" = $3
      and "asset"."thumbhash" is not null
    union
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $4
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $5
      and "asset"."type" = $6
      and "asset"."thumbhash" is not null
  ) as "combined"
order by
  "combined"."fileCreatedAt" desc
limit
  $7

-- SharedSpaceRepository.getLastAssetAddedAt
select
  max("addedAt") as "lastAddedAt"
from
  "shared_space_asset"
where
  "spaceId" = $1

-- SharedSpaceRepository.getNewAssetCount
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "shared_space_asset"."addedAt" > $2
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $4
      and "asset"."createdAt" > $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
  ) as "combined"

-- SharedSpaceRepository.getLastContributor
select
  "user"."id",
  "user"."name"
from
  "shared_space_asset"
  inner join "user" on "user"."id" = "shared_space_asset"."addedById"
  and "user"."deletedAt" is null
where
  "shared_space_asset"."spaceId" = $1
  and "shared_space_asset"."addedAt" > $2
order by
  "shared_space_asset"."addedAt" desc
limit
  $3

-- SharedSpaceRepository.updateMemberLastViewed
update "shared_space_member"
set
  "lastViewedAt" = $1
where
  "spaceId" = $2
  and "userId" = $3

-- SharedSpaceRepository.getContributionCounts
select
  "addedById",
  count(*) as "count"
from
  "shared_space_asset"
where
  "spaceId" = $1
group by
  "addedById"

-- SharedSpaceRepository.getMemberActivity
select
  "addedById",
  max("addedAt") as "lastAddedAt",
  (
    select
      "ssa2"."assetId"
    from
      "shared_space_asset" as "ssa2"
    where
      "ssa2"."addedById" = "shared_space_asset"."addedById"
      and "ssa2"."spaceId" = $1
    order by
      "ssa2"."addedAt" desc
    limit
      $2
  ) as "recentAssetId"
from
  "shared_space_asset"
where
  "spaceId" = $3
group by
  "addedById"

-- SharedSpaceRepository.getMapMarkers
select
  "asset"."id",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $3
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $4
  ) as "combined"
  inner join "asset" on "asset"."id" = "combined"."id"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null

-- SharedSpaceRepository.getFilteredMapMarkers
select
  "asset"."id",
  "asset_exif"."latitude" as "lat",
  "asset_exif"."longitude" as "lon",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."ownerId" = any ($2::uuid[])
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null

-- SharedSpaceRepository.getActivities
select
  "shared_space_activity"."id",
  "shared_space_activity"."type",
  "shared_space_activity"."data",
  "shared_space_activity"."createdAt",
  "shared_space_activity"."userId",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."avatarColor"
from
  "shared_space_activity"
  left join "user" on "user"."id" = "shared_space_activity"."userId"
where
  "shared_space_activity"."spaceId" = $1
order by
  "shared_space_activity"."createdAt" desc
limit
  $2
offset
  $3

-- SharedSpaceRepository.hasPetsBySpaceId
select
  count(*) as "count"
from
  "shared_space_person"
where
  "spaceId" = $1
  and "type" = $2

-- SharedSpaceRepository.getPersonsBySpaceId
select
  "shared_space_person".*,
  "person"."name" as "personalName",
  "person"."thumbnailPath" as "personalThumbnailPath"
from
  "shared_space_person"
  left join "asset_face" on "asset_face"."id" = "shared_space_person"."representativeFaceId"
  left join "person" on "person"."id" = "asset_face"."personId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person"."isHidden" = $2
order by
  CASE
    WHEN shared_space_person.name != '' THEN 0
    WHEN person.name IS NOT NULL
    AND person.name != '' THEN 0
    ELSE 1
  END,
  "shared_space_person"."assetCount" desc,
  COALESCE(
    NULLIF(shared_space_person.name, ''),
    NULLIF(person.name, '')
  ) asc nulls last,
  "shared_space_person"."id"
limit
  $3

-- SharedSpaceRepository.getPersonById
select
  "shared_space_person".*,
  "person"."name" as "personalName",
  "person"."thumbnailPath" as "personalThumbnailPath"
from
  "shared_space_person"
  left join "asset_face" on "asset_face"."id" = "shared_space_person"."representativeFaceId"
  left join "person" on "person"."id" = "asset_face"."personId"
where
  "shared_space_person"."id" = $1

-- SharedSpaceRepository.updatePerson
update "shared_space_person"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.deletePerson
delete from "shared_space_person"
where
  "id" = $1

-- SharedSpaceRepository.getPersonAssetIds
select distinct
  "asset_face"."assetId"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person_face"."personId" = $1

-- SharedSpaceRepository.reassignPersonFacesSafe
delete from "shared_space_person_face"
where
  "personId" = $1
  and "assetFaceId" in (
    select
      "assetFaceId"
    from
      "shared_space_person_face"
    where
      "personId" = $2
  )
update "shared_space_person_face"
set
  "personId" = $1
where
  "personId" = $2

-- SharedSpaceRepository.getFirstFaceIdForPerson
select
  "shared_space_person_face"."assetFaceId"
from
  "shared_space_person_face"
  inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person_face"."personId" = $1
limit
  $2

-- SharedSpaceRepository.repairOrphanedRepresentativeFaces
update "shared_space_person"
set
  "representativeFaceId" = (
    select
      "shared_space_person_face"."assetFaceId"
    from
      "shared_space_person_face"
      inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
    where
      "shared_space_person_face"."personId" = "shared_space_person"."id"
    limit
      $1
  )
where
  "shared_space_person"."spaceId" = $2
  and "shared_space_person"."representativeFaceId" is null
  and exists (
    select
    from
      "shared_space_person_face"
    where
      "shared_space_person_face"."personId" = "shared_space_person"."id"
  )

-- SharedSpaceRepository.removePersonFacesByAssetIds
select distinct
  "personId"
from
  "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
    where
      "asset_face"."assetId" in ($1)
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )
delete from "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
    where
      "asset_face"."assetId" in ($1)
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )

-- SharedSpaceRepository.removePersonFacesByLibrary
select distinct
  "personId"
from
  "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset"."libraryId" = $1
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )
delete from "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset"."libraryId" = $1
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )

-- SharedSpaceRepository.deleteOrphanedPersons
delete from "shared_space_person"
where
  "spaceId" = $1
  and "id" not in (
    select
      "personId"
    from
      "shared_space_person_face"
  )

-- SharedSpaceRepository.deleteAllOrphanedPersons
delete from "shared_space_person"
where
  "id" not in (
    select
      "personId"
    from
      "shared_space_person_face"
  )

-- SharedSpaceRepository.deleteAllPersonFaces
delete from "shared_space_person_face"

-- SharedSpaceRepository.deleteAllPersons
delete from "shared_space_person"

-- SharedSpaceRepository.recountPersons
update "shared_space_person"
set
  "faceCount" = (
    select
      count(*) as "count"
    from
      "shared_space_person_face"
      inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."visibility" = 'timeline'
      and "shared_space_person_face"."personId" = "shared_space_person"."id"
  ),
  "assetCount" = (
    select
      count(distinct ("asset_face"."assetId")) as "count"
    from
      "shared_space_person_face"
      inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."visibility" = 'timeline'
      and "shared_space_person_face"."personId" = "shared_space_person"."id"
  )
where
  "id" in ($1)

-- SharedSpaceRepository.getAlias
select
  *
from
  "shared_space_person_alias"
where
  "personId" = $1
  and "userId" = $2

-- SharedSpaceRepository.deleteAlias
delete from "shared_space_person_alias"
where
  "personId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getAliasesBySpaceAndUser
select
  "shared_space_person_alias".*
from
  "shared_space_person_alias"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_alias"."personId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person_alias"."userId" = $2

-- SharedSpaceRepository.migrateAliases
select
  *
from
  "shared_space_person_alias"
where
  "personId" = $1
delete from "shared_space_person_alias"
where
  "personId" = $1

-- SharedSpaceRepository.findClosestSpacePerson
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "shared_space_person"."id" as "personId",
      "shared_space_person"."name",
      face_search.embedding <=> $1 as "distance"
    from
      "shared_space_person"
      inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
      inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
    where
      "shared_space_person"."spaceId" = $2
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
commit

-- SharedSpaceRepository.getSpacePersonsWithEmbeddings
select
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."type",
  "shared_space_person"."isHidden",
  "shared_space_person"."faceCount",
  "shared_space_person"."representativeFaceId",
  "face_search"."embedding"
from
  "shared_space_person"
  inner join "face_search" on "face_search"."faceId" = "shared_space_person"."representativeFaceId"
where
  "shared_space_person"."spaceId" = $1

-- SharedSpaceRepository.getAssetFacesForMatching
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."personId",
  "face_search"."embedding"
from
  "asset_face"
  inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
where
  "asset_face"."assetId" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true

-- SharedSpaceRepository.isAssetInSpace
select
  "combined"."id"
from
  (
    select
      "assetId" as "id"
    from
      "shared_space_asset"
    where
      "spaceId" = $1
      and "assetId" = $2
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $3
      and "asset"."id" = $4
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $5
  ) as "combined"
limit
  $6

-- SharedSpaceRepository.isFaceInSpace
select
  "combined"."id"
from
  (
    select
      "asset_face"."id"
    from
      "shared_space_asset"
      inner join "asset_face" on "asset_face"."assetId" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset_face"."id" = $2
      and "asset_face"."deletedAt" is null
    union
    select
      "asset_face"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
    where
      "shared_space_library"."spaceId" = $3
      and "asset_face"."id" = $4
      and "asset_face"."deletedAt" is null
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $5
  ) as "combined"
limit
  $6

-- SharedSpaceRepository.getAssetIdsInSpace
select
  "combined"."id" as "assetId"
from
  (
    select
      "assetId" as "id"
    from
      "shared_space_asset"
    where
      "spaceId" = $1
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $2
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
  ) as "combined"

-- SharedSpaceRepository.getSpaceIdsForAsset
select
  "combined"."spaceId"
from
  (
    select
      "shared_space_asset"."spaceId"
    from
      "shared_space_asset"
      inner join "shared_space" on "shared_space"."id" = "shared_space_asset"."spaceId"
    where
      "shared_space_asset"."assetId" = $1
      and "shared_space"."faceRecognitionEnabled" = $2
    union
    select
      "shared_space_library"."spaceId"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      inner join "shared_space" on "shared_space"."id" = "shared_space_library"."spaceId"
    where
      "asset"."id" = $3
      and "shared_space"."faceRecognitionEnabled" = $4
  ) as "combined"

-- SharedSpaceRepository.isPersonFaceAssigned
select
  "shared_space_person_face"."assetFaceId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "shared_space_person_face"."assetFaceId" = $1
  and "shared_space_person"."spaceId" = $2
limit
  $3

-- SharedSpaceRepository.getPetFacesForAsset
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."personId"
from
  "asset_face"
  inner join "person" on "person"."id" = "asset_face"."personId"
where
  "asset_face"."assetId" = $1
  and "asset_face"."deletedAt" is null
  and "person"."type" = $2

-- SharedSpaceRepository.findSpacePersonByLinkedPersonId
select
  "shared_space_person".*
from
  "shared_space_person"
  inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person"."spaceId" = $1
  and "asset_face"."personId" = $2
limit
  $3

-- SharedSpaceRepository.findSpacePersonsByLinkedPersonIds
select
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."isHidden",
  "shared_space_person"."birthDate",
  "shared_space_person"."updatedAt",
  "shared_space_person"."type",
  "person"."name" as "personalName",
  "person"."thumbnailPath" as "personalThumbnailPath",
  "asset_face"."personId"
from
  "shared_space_person"
  inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  left join "asset_face" as "representative_face" on "representative_face"."id" = "shared_space_person"."representativeFaceId"
  left join "person" on "person"."id" = "representative_face"."personId"
where
  "shared_space_person"."spaceId" = $1
  and "asset_face"."personId" in ($2)
group by
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."isHidden",
  "shared_space_person"."birthDate",
  "shared_space_person"."updatedAt",
  "shared_space_person"."type",
  "person"."name",
  "person"."thumbnailPath",
  "asset_face"."personId"

-- SharedSpaceRepository.findSpaceForAssetAndUser
select
  "combined"."spaceId"
from
  (
    select
      "shared_space_asset"."spaceId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      and "asset"."deletedAt" is null
    where
      "shared_space_asset"."assetId" = $1
      and "shared_space_member"."userId" = $2
    union
    select
      "shared_space_library"."spaceId"
    from
      "shared_space_library"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      and "asset"."id" = $3
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $4
    where
      "shared_space_member"."userId" = $5
  ) as "combined"
limit
  $6
