-- NOTE: This file is auto generated by ./sql-generator

-- StorageTargetRepository.getAll
select
  "storage_target".*
from
  "storage_target"
order by
  "name" asc

-- StorageTargetRepository.get
select
  "storage_target".*
from
  "storage_target"
where
  "id" = $1

-- StorageTargetRepository.getByName
select
  "storage_target".*
from
  "storage_target"
where
  "name" = $1

-- StorageTargetRepository.getTransfer
select
  "storage_target_transfer".*
from
  "storage_target_transfer"
where
  "id" = $1

-- StorageTargetRepository.getTransfers
select
  "storage_target_transfer".*
from
  "storage_target_transfer"
where
  "targetId" = $1
order by
  "createdAt" desc
limit
  $2

-- StorageTargetRepository.streamAssetsForExport
select
  "asset"."id"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."isExternal" = $2
  and "asset"."isOffline" = $3
  and "asset"."visibility" != $4

-- StorageTargetRepository.getAssetForExport
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."checksum",
  "asset"."type",
  "asset_exif"."fileSizeInByte"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."id" = $1

-- StorageTargetRepository.getObjectByAsset
select
  "storage_target_object".*
from
  "storage_target_object"
where
  "targetId" = $1
  and "assetId" = $2

-- StorageTargetRepository.filterNewRemoteKeys
select
  "remoteKey"
from
  "storage_target_object"
where
  "targetId" = $1
  and "remoteKey" in ($2)
