-- NOTE: This file is auto generated by ./sql-generator

-- SyncNodeRepository.getAll
select
  "sync_node".*
from
  "sync_node"
order by
  "name" asc

-- SyncNodeRepository.get
select
  "sync_node".*
from
  "sync_node"
where
  "id" = $1

-- SyncNodeRepository.getByName
select
  "sync_node".*
from
  "sync_node"
where
  "name" = $1

-- SyncNodeRepository.getPairings
select
  "sync_node_user".*
from
  "sync_node_user"
where
  "nodeId" = $1
order by
  "createdAt" asc

-- SyncNodeRepository.getPairing
select
  "sync_node_user".*
from
  "sync_node_user"
where
  "id" = $1

-- SyncNodeRepository.getSyncablePairings
select
  "sync_node_user"."id" as "id",
  "sync_node_user"."nodeId" as "nodeId",
  "sync_node_user"."localUserId" as "localUserId",
  "sync_node_user"."remoteUserId" as "remoteUserId",
  "sync_node_user"."pushEnabled" as "pushEnabled",
  "sync_node_user"."pullEnabled" as "pullEnabled"
from
  "sync_node_user"
  inner join "sync_node" on "sync_node"."id" = "sync_node_user"."nodeId"
where
  "sync_node"."isEnabled" = $1
  and (
    "sync_node_user"."pushEnabled" = $2
    or "sync_node_user"."pullEnabled" = $3
  )

-- SyncNodeRepository.getAssetMapping
select
  "sync_node_asset".*
from
  "sync_node_asset"
where
  "nodeUserId" = $1
  and "localAssetId" = $2

-- SyncNodeRepository.getMappedRemoteIds
select
  "remoteAssetId"
from
  "sync_node_asset"
where
  "nodeUserId" = $1
  and "remoteAssetId" in ($2)

-- SyncNodeRepository.getMappingByRemoteId
select
  "sync_node_asset".*
from
  "sync_node_asset"
where
  "nodeUserId" = $1
  and "remoteAssetId" = $2

-- SyncNodeRepository.getAlbumMappings
select
  "sync_node_album".*
from
  "sync_node_album"
where
  "nodeUserId" = $1

-- SyncNodeRepository.getChangedAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."checksum",
  "asset"."type",
  "asset"."isFavorite",
  "asset"."visibility",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."deletedAt",
  "asset"."updateId",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset_exif"."description"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."updateId" > $2
order by
  "asset"."updateId" asc
limit
  $3

-- SyncNodeRepository.getAlbumsForOwner
select
  "album"."id",
  "album"."albumName",
  "album"."description"
from
  "album"
where
  "album"."deletedAt" is null
  and exists (
    select
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."role" = $1
      and "album_user"."userId" = $2
  )

-- SyncNodeRepository.getAlbumAssetIds
select
  "album_asset"."assetId"
from
  "album_asset"
  inner join "asset" on "asset"."id" = "album_asset"."assetId"
where
  "album_asset"."albumId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" != $2
