-- NOTE: This file is auto generated by ./sql-generator

-- TagRepository.get
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "id" = $1

-- TagRepository.getByValue
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "userId" = $1
  and "value" = $2

-- TagRepository.upsertValue
with
  "created_tag" as (
    insert into
      "tag" ("userId", "value", "parentId")
    values
      ($1, $2, $3)
    on conflict ("userId", "value") do update
    set
      "parentId" = $4
    returning
      *
  ),
  "created_tag_closures" as (
    insert into
      "tag_closure" ("id_ancestor", "id_descendant")
    select
      "created_tag"."id" as "id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
    union all
    select
      "tag_closure"."id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
      inner join "tag_closure" on "tag_closure"."id_descendant" = "created_tag"."parentId"
    on conflict do nothing
  )
select
  *
from
  "created_tag"

-- TagRepository.getAll
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "userId" = $1
order by
  "value"

-- TagRepository.create
with
  "created_tag" as (
    insert into
      "tag" ("userId", "color", "value")
    values
      ($1, $2, $3)
    returning
      *
  ),
  "created_tag_closures" as (
    insert into
      "tag_closure" ("id_ancestor", "id_descendant")
    select
      "created_tag"."id" as "id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
    union all
    select
      "tag_closure"."id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
      inner join "tag_closure" on "tag_closure"."id_descendant" = "created_tag"."parentId"
    on conflict do nothing
  )
select
  *
from
  "created_tag"

-- TagRepository.update
begin
select
  "value"
from
  "tag"
where
  "id" = $1
update "tag"
set
  "value" = $1,
  "color" = $2
where
  "id" = $3
returning
  *
rollback

-- TagRepository.delete
delete from "tag"
where
  "id" = $1

-- TagRepository.addAssetIds
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)

-- TagRepository.removeAssetIds
delete from "tag_asset"
where
  "tagId" = $1
  and "assetId" in ($2)

-- TagRepository.upsertAssetIds
insert into
  "tag_asset" ("assetId", "tagIds")
values
  ($1, $2)
on conflict do nothing
returning
  *

-- TagRepository.replaceAssetTags
begin
delete from "tag_asset"
where
  "assetId" = $1
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)
on conflict do nothing
returning
  *
rollback
