-- NOTE: This file is auto generated by ./sql-generator

-- TranscriptRepository.getByAssetId
select
  "transcript_segment".*
from
  "transcript_segment"
where
  "transcript_segment"."assetId" = $1
order by
  "transcript_segment"."startTime" asc

-- TranscriptRepository.getStatus
select
  "asset_job_status"."transcribedAt",
  "asset_job_status"."transcriptionProgressMs"
from
  "asset_job_status"
where
  "asset_job_status"."assetId" = $1

-- TranscriptRepository.getLastLanguage
select
  "transcript_segment"."language"
from
  "transcript_segment"
where
  "transcript_segment"."assetId" = $1
order by
  "transcript_segment"."startTime" desc
limit
  $2

-- TranscriptRepository.reset
begin
delete from "transcript_segment"
where
  "assetId" = $1
  and "correctedText" is null
delete from "transcript_search"
where
  "assetId" = $1
insert into
  "asset_job_status" ("assetId", "transcriptionProgressMs")
values
  ($1, $2)
on conflict ("assetId") do update
set
  "transcriptionProgressMs" = $3
rollback

-- TranscriptRepository.updateSegment
update "transcript_segment"
set
  "correctedText" = $1
where
  "id" = $2
  and "assetId" = $3
returning
  *

-- TranscriptRepository.upsertSearchText
insert into
  "transcript_search" ("assetId", "text")
values
  ($1, $2)
on conflict ("assetId") do update
set
  "text" = "excluded"."text"

-- TranscriptRepository.appendChunk
begin
insert into
  "transcript_segment" (
    "assetId",
    "startTime",
    "endTime",
    "text",
    "language",
    "noSpeechProbability",
    "avgLogProbability",
    "compressionRatio"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8)
rollback
