-- NOTE: This file is auto generated by ./sql-generator

-- VersionHistoryRepository.getAll
select
  *
from
  "version_history"
order by
  "createdAt" desc

-- VersionHistoryRepository.getLatest
select
  *
from
  "version_history"
order by
  "createdAt" desc

-- VersionHistoryRepository.create
insert into
  "version_history" ("version")
values
  ($1)
returning
  *
