-- NOTE: This file is auto generated by ./sql-generator

-- VideoFrameRepository.upsertFrames
insert into
  "video_frames" ("0", "assetId")
values
  ($1, $2)
on conflict ("assetId") do update
set
  "0" = $3

-- VideoFrameRepository.deleteFrames
delete from "video_frames"
where
  "assetId" = $1

-- VideoFrameRepository.getFrames
select
  *
from
  "video_frames"
where
  "assetId" = $1
