global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: immich_api
    static_configs:
      - targets: ['immich-server:8081']

  - job_name: immich_microservices
    static_configs:
      - targets: ['immich-server:8082']

  - job_name: immich_machine_learning
    metrics_path: /metrics
    static_configs:
      - targets: ['immich-machine-learning:3003']
