-- NOTE: This file is auto generated by ./sql-generator

-- SmartInfoRepository.searchCLIP
START TRANSACTION
SET
  LOCAL vectors.k = '100'
SET
  LOCAL vectors.enable_prefilter = on
ROLLBACK

-- SmartInfoRepository.searchFaces
START TRANSACTION
SET
  LOCAL vectors.k = '100'
ROLLBACK
