import type { TakeoutAlbum } from '$lib/utils/google-takeout-parser';
import type { ScanProgress, ScanResult } from '$lib/utils/google-takeout-scanner';
import { SvelteSet } from 'svelte/reactivity';

export enum ImportStep {
  Source = 0,
  Files = 1,
  Scan = 2,
  Review = 3,
  Import = 4,
}

export interface ImportOptions {
  importFavorites: boolean;
  importArchived: boolean;
  importDescriptions: boolean;
  skipDuplicates: boolean;
}

export interface ImportProgress {
  imported: number;
  skipped: number;
  errors: number;
  total: number;
  currentFile: string;
  currentAlbum: string;
  albumsCreated: number;
  errorLog: Array<{ file: string; error: string }>;
}

function defaultOptions(): ImportOptions {
  return {
    importFavorites: true,
    importArchived: true,
    importDescriptions: true,
    skipDuplicates: true,
  };
}

function defaultProgress(): ImportProgress {
  return {
    imported: 0,
    skipped: 0,
    errors: 0,
    total: 0,
    currentFile: '',
    currentAlbum: '',
    albumsCreated: 0,
    errorLog: [],
  };
}

export class ImportManager {
  currentStep = $state<ImportStep>(ImportStep.Source);
  selectedFiles = $state<File[]>([]);
  scanResult = $state<ScanResult | undefined>(undefined);
  scanProgress = $state<ScanProgress | undefined>(undefined);
  selectedAlbums = $state<Set<string>>(new SvelteSet());
  options = $state<ImportOptions>(defaultOptions());
  importProgress = $state<ImportProgress>(defaultProgress());
  isPaused = $state<boolean>(false);
  isComplete = $state<boolean>(false);

  totalSize = $derived(this.selectedFiles.reduce((sum, file) => sum + file.size, 0));

  nextStep() {
    if (this.currentStep < ImportStep.Import) {
      this.currentStep++;
    }
  }

  previousStep() {
    if (this.currentStep > ImportStep.Source) {
      this.currentStep--;
    }
  }

  reset() {
    this.currentStep = ImportStep.Source;
    this.selectedFiles = [];
    this.scanResult = undefined;
    this.scanProgress = undefined;
    this.selectedAlbums = new SvelteSet();
    this.options = defaultOptions();
    this.importProgress = defaultProgress();
    this.isPaused = false;
    this.isComplete = false;
  }

  addFiles(files: File[]) {
    this.selectedFiles = [...this.selectedFiles, ...files];
  }

  clearFiles() {
    this.selectedFiles = [];
  }

  setAlbums(albums: TakeoutAlbum[]) {
    this.selectedAlbums = new SvelteSet(albums.filter((a) => !a.isAutoGenerated).map((a) => a.name));
  }

  toggleAlbum(name: string) {
    const next = new SvelteSet(this.selectedAlbums);
    if (next.has(name)) {
      next.delete(name);
    } else {
      next.add(name);
    }
    this.selectedAlbums = next;
  }

  selectAllAlbums() {
    if (!this.scanResult) {
      return;
    }
    this.selectedAlbums = new SvelteSet(this.scanResult.albums.map((a) => a.name));
  }

  deselectAllAlbums() {
    this.selectedAlbums = new SvelteSet();
  }

  setOption<K extends keyof ImportOptions>(key: K, value: ImportOptions[K]) {
    this.options = { ...this.options, [key]: value };
  }

  trackImported() {
    this.importProgress = { ...this.importProgress, imported: this.importProgress.imported + 1 };
  }

  trackSkipped() {
    this.importProgress = { ...this.importProgress, skipped: this.importProgress.skipped + 1 };
  }

  trackError(file: string, error: string) {
    this.importProgress = {
      ...this.importProgress,
      errors: this.importProgress.errors + 1,
      errorLog: [...this.importProgress.errorLog, { file, error }],
    };
  }

  togglePause() {
    this.isPaused = !this.isPaused;
  }
}
