/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpDto
 */
export interface SignUpDto {
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the SignUpDto interface.
 */
export function instanceOfSignUpDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function SignUpDtoFromJSON(json: any): SignUpDto {
    return SignUpDtoFromJSONTyped(json, false);
}

export function SignUpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function SignUpDtoToJSON(value?: SignUpDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
    };
}

