/* tslint:disable */
/* eslint-disable */
/**
 * Immich
 * Immich API
 *
 * The version of the OpenAPI document: 1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    profileImagePath: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponseDto
     */
    shouldChangePassword: boolean;
}

/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "profileImagePath" in value;
    isInstance = isInstance && "shouldChangePassword" in value;

    return isInstance;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'createdAt': json['createdAt'],
        'profileImagePath': json['profileImagePath'],
        'shouldChangePassword': json['shouldChangePassword'],
    };
}

export function UserResponseDtoToJSON(value?: UserResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'createdAt': value.createdAt,
        'profileImagePath': value.profileImagePath,
        'shouldChangePassword': value.shouldChangePassword,
    };
}

