include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
