# .github/workflows/sync-and-build.yml
name: Sync Immich Release & Build Images

on:
  schedule:
    # every hour; adjust as you like
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write        # to update branches
  packages: write        # to push to GHCR
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    # expose the fetched tag to downstream jobs
    outputs:
      release_tag: ${{ steps.get_release.outputs.tag }}
    steps:
      - name: Get latest Immich release tag
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: 'immich-app',
              repo: 'immich',
            });
            return latest.data.tag_name;
          result-encoding: string
        # now get_release.outputs.tag == e.g. "v1.134.0"

      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # we need full history to push branches/tags

      - name: Add Immich upstream remote
        run: |
          git remote add upstream https://github.com/immich-app/immich.git
          git fetch upstream --tags

      - name: Update `dockerimageML` branch
        run: |
          git branch -f dockerimageML ${{ steps.get_release.outputs.tag }}
          git push origin dockerimageML --force

  build:
    needs: sync
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.sync.outputs.release_tag }}
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Checkout `dockerimageML`
        uses: actions/checkout@v4
        with:
          ref: dockerimageML

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # === Server image ===
      - name: Build & push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_REPO }}/immich-server:${{ env.IMAGE_TAG }}

      # === ML images (CPU + CUDA) ===
      - name: Build & push ML images
        uses: docker/build-push-action@v6
        strategy:
          matrix:
            device: [cpu, cuda]
        with:
          context: machine-learning
          file: machine-learning/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            DEVICE=${{ matrix.device }}
          tags: |
            ${{ env.GHCR_REPO }}/immich-machine-learning:${{ env.IMAGE_TAG }}${{ matrix.device == 'cuda' && '-cuda' || '' }}
