# .github/workflows/sync-and-build.yml
name: Sync Immich Release & Build Images

on:
  schedule:
    - cron: '0 * * * *'    # every hour
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_release.outputs.tag }}
    steps:
      - name: Get latest Immich release tag
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: 'immich-app',
              repo: 'immich',
            });
            return latest.data.tag_name;
          result-encoding: string

      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Immich upstream remote & fetch
        run: |
          git remote add upstream https://github.com/immich-app/immich.git
          git fetch upstream --tags

      - name: Update `dockerimageML` branch
        run: |
          git branch -f dockerimageML ${{ steps.get_release.outputs.tag }}
          git push origin dockerimageML --force

  build-server:
    needs: sync
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.sync.outputs.release_tag }}
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Checkout `dockerimageML`
        uses: actions/checkout@v4
        with:
          ref: dockerimageML

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_REPO }}/immich-server:${{ env.IMAGE_TAG }}

  build-ml:
    needs: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - device: cpu
            suffix: ""
            dockerfile: Dockerfile
          - device: cuda
            suffix: "-cuda"
            dockerfile: Dockerfile
    env:
      IMAGE_TAG: ${{ needs.sync.outputs.release_tag }}
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Checkout `dockerimageML`
        uses: actions/checkout@v4
        with:
          ref: dockerimageML

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push ML image (${{ matrix.device }})
        uses: docker/build-push-action@v6
        with:
          context: machine-learning
          file: machine-learning/${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          build-args: |
            DEVICE=${{ matrix.device }}
          tags: |
            ${{ env.GHCR_REPO }}/immich-machine-learning:${{ env.IMAGE_TAG }}${{ matrix.suffix }}
