name: Sync Immich Release and Build Docker Images

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    env:
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}/immich-server
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: dockerimageML

      - name: Get latest release tag from source repo
        id: get_release
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/immich-app/immich/releases/latest | jq -r .tag_name)
          echo "Latest tag is $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"
        shell: bash

      - name: Check if latest release already exists in this branch
        id: check_existing
        run: |
          if git ls-remote --exit-code --heads origin dockerimageML | grep -q "${{ steps.get_release.outputs.latest_tag }}"; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV

      - name: Clone latest release from upstream if new
        if: env.exists == 'false'
        run: |
          git clone --depth 1 --branch "${{ steps.get_release.outputs.latest_tag }}" https://github.com/immich-app/immich temp-clone
          rsync -a --delete temp-clone/ ./
          rm -rf temp-clone
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync immich release ${{ steps.get_release.outputs.latest_tag }}"
          git push origin HEAD:dockerimageML

      - name: Trigger Docker Build Workflow
        if: env.exists == 'false'
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: Custom_Build.yml
          ref: dockerimageML
          inputs:
            tag: ${{ steps.get_release.outputs.latest_tag }}
